This is notebook 2 for data cleaning, manipulation, and merging the four web-scraped files to form two datasets (primary and secondary), then clean, merge, and form a single final dataset.

## 2. Data Cleaning and Manipulation

### 1. Data Cleaning and Manipulation on Basic Stats, Advanced Stats and Country Data

In this section, we will conduct data cleaning and manipulation on the Basic Stats, Advanced Stats, and Bio Data datasets, with the objective of merging them into an unified dataset for future use.

In [ ]:
# import pertinent libraries for data curation and manipulation
import pandas as pd
import numpy as np

# read datasets for primary dataset of base, advanced NBA Statistics and secondary NBA players' countries dataset
player_info_base = pd.read_csv('Player_Base_Statistics.csv')
player_info_advanced = pd.read_csv('Player_Advanced_Statistics.csv')
player_bio = pd.read_csv('Player_Country.csv')

In [ ]:
# change country names that not USA as international
player_bio.loc[player_bio["COUNTRY"] != "USA", "COUNTRY"] = "international"

In [ ]:
# Concatenate 'COUNTRY' column from player_bio into player_info_base
player_info_base = pd.concat([player_info_base, player_bio["COUNTRY"]], axis=1)

In [ ]:
# display all overlapping columns within player_info_advanced and drop them from player_info_advanced.
# we only keep columns PLAYER_ID','season_id as keys for merging later
overlapping_cols = [
    "PLAYER_NAME",
    "NICKNAME",
    "TEAM_ID",
    "TEAM_ABBREVIATION",
    "AGE",
    "GP",
    "W",
    "L",
    "W_PCT",
    "MIN",
    "FGM",
    "FGA",
    "FG_PCT",
    "GP_RANK",
    "W_RANK",
    "L_RANK",
    "W_PCT_RANK",
    "MIN_RANK",
    "FGM_RANK",
    "FGA_RANK",
    "FG_PCT_RANK",
]

advanced_update = player_info_advanced.drop(overlapping_cols, axis=1)

In [ ]:
# merge player_info_base and advanced_update data into Merged_Stats
player_statistics_country = player_info_base.merge(
    advanced_update, on=["PLAYER_ID", "season_id"], how="inner"
)

# extract the start year of the season_id and convert it as integer type
player_statistics_country["season_id"] = player_statistics_country["season_id"].apply(
    lambda x: x[0:4]
)
player_statistics_country["season_id"] = player_statistics_country["season_id"].astype(
    int
)

Now that we have the merged dataset named 'player_statistics_country,' our next step involves manipulating the PLAYER_NAME column. This manipulation is necessary to ensure alignment in format between this dataset and the salary dataset. We will merge these datasets in the future based on player names and years, so it's important to harmonize the format.

In [ ]:
# eliminate special characters in PLAYER_NAME column
def clean_player_names(df, suffixes_to_remove):
    """The purpose of this function is to eliminate 
    the special characters in the PLAYER_NAME column.
    
    It accepts the following parameters:
        1) the dataframe to be cleaned
        2) a list of special characters to be removed
    """

    for suffix in suffixes_to_remove:
        df['PLAYER_NAME'] = df['PLAYER_NAME'].str.replace(suffix, "", regex=True)
    return df

suffixes_to_remove = ["\."," Jr"," Sr"," III"," II"," IV"]
clean_player_names(player_statistics_country, suffixes_to_remove)

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,EFG_PCT_RANK,TS_PCT_RANK,USG_PCT_RANK,E_USG_PCT_RANK,E_PACE_RANK,PACE_RANK,sp_work_PACE_RANK,PIE_RANK,FGM_PG_RANK,FGA_PG_RANK
0,920,AC Green,A.C.,1610612742,DAL,33.0,83,23,60,0.277,...,203,213,404,406,348,372,372,135,191,199
1,243,Aaron McKie,Aaron,1610612765,DET,24.0,83,48,35,0.578,...,256,209,355,351,392,361,361,152,264,258
2,1425,Aaron Williams,Aaron,1610612763,VAN,25.0,33,4,29,0.121,...,17,26,289,280,390,362,362,81,202,253
3,768,Acie Earl,Acie,1610612749,MIL,27.0,47,14,33,0.298,...,400,389,94,91,231,173,173,332,304,289
4,228,Adam Keefe,Adam,1610612762,UTA,27.0,62,48,14,0.774,...,108,59,392,393,280,282,282,213,320,351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12841,1628380,Zach Collins,Zach,1610612759,SAS,25.0,63,20,43,0.317,...,164,172,130,134,47,86,86,132,132,153
12842,203897,Zach LaVine,Zach,1610612741,CHI,28.0,77,38,39,0.494,...,203,146,30,30,374,409,409,77,24,25
12843,1630192,Zeke Nnaji,Zeke,1610612743,DEN,22.0,53,34,19,0.642,...,83,105,362,358,495,472,472,373,337,377
12844,1630533,Ziaire Williams,Ziaire,1610612763,MEM,21.0,37,21,16,0.568,...,408,435,233,234,98,162,162,476,308,293
12845,1629627,Zion Williamson,Zion,1610612740,NOP,22.0,29,17,12,0.586,...,68,55,23,25,125,234,234,15,12,44

In [ ]:
# eliminate middle names in the PLAYER_NAME column if there is any
stats_first_name = (
    player_statistics_country["PLAYER_NAME"].str.split(" ").apply(lambda x: x[0])
)
stats_last_name = (
    player_statistics_country["PLAYER_NAME"].str.split(" ").apply(lambda x: x[-1])
)

player_statistics_country["PLAYER_NAME"] = stats_first_name + " " + stats_last_name

In [ ]:
# # eliminate middle names in the PLAYER_NAME column if there is any
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace("\.", "", regex = True)
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace(" Jr", "", regex = True)
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace(" Sr", "", regex = True)
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace(" III", "", regex = True)
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace(" II", "", regex = True)
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace(" IV", "", regex = True)


# stats_first_name = (
#     player_statistics_country["PLAYER_NAME"].str.split(" ").apply(lambda x: x[0])
# )
# stats_last_name = (
#     player_statistics_country["PLAYER_NAME"].str.split(" ").apply(lambda x: x[-1])
# )

# player_statistics_country["PLAYER_NAME"] = stats_first_name + " " + stats_last_name

In [ ]:
#check shape of the merged player statistics and country dataframe
player_statistics_country.shape

(12846, 124)

We have successfully completed all the necessary cleaning, manipulation, and merging tasks on the merged statistics dataset 'player_statistics_country'. In the next section, we will work on salary dataset.

### 2. Data Cleaning and Manipulation on Salary Data

In [ ]:
import pandas as pd
import numpy as np

# read the tertiary salary dataset
df_sal = pd.read_csv("Player_Salary.csv")

In [ ]:
#observe for missing, NaN values, and data types
print(df_sal.head(20))
print(df_sal.sample(20))
df_sal.tail(20)

    Rank                                             Player Signed Age  Yrs  \
0      1  Stephen Curry  Point Guard | 2022-2025 (FA: 2026)         33    4
1      2    Luka Doncic  Point Guard | 2022-2026 (FA: 2027)         22    5
2      2     Trae Young  Point Guard | 2022-2026 (FA: 2027)         22    5
3      4  Russell Westbrook  Point Guard | 2018-2022 (FA...         28    5
4      5    LaMelo Ball  Point Guard | 2024-2028 (FA: 2029)         21    5
5      5  Tyrese Haliburton  Point Guard | 2024-2028 (FA...         23    5
6      7  Stephen Curry  Point Guard | 2017-2021 (FA: 2022)         29    5
7      8      Ja Morant  Point Guard | 2023-2027 (FA: 2028)         22    5
8      8  Darius Garland  Point Guard | 2023-2027 (FA: 2...         22    5
9     10  Shai Gilgeous-Alexander  Point Guard | 2022-20...         23    5
10    11  Ben Simmons  Point Guard | 2020-2024 (FA: 2025...         22    5
11    12  Damian Lillard  Point Guard | 2021-2024 (FA: 2...         28    4
12    13  John Wall  Point Guard | 2019-2022 (FA: 2023) ...         26    4
13    14   De'Aaron Fox  Point Guard | 2021-2025 (FA: 2026)         22    5
14    15  Chris Paul  Point Guard | 2018-2021 (FA: 2022)...         33    4
15    16   Jamal Murray  Point Guard | 2020-2024 (FA: 2025)         22    5
16    17  Mike Conley  Point Guard | 2016-2020 (FA: 2021...         28    5
17    18  Kemba Walker  Point Guard | 2019-2023 (FA: 202...         29    4
18    19    Damian Lillard  Point Guard | 2016-2020 (FA: 0)         24    5
19    20  Kyrie Irving  Point Guard | 2019-2022 (FA: 202...         27    4

           Value          AAV Sign Bonus
0   $215,353,664  $53,838,416        NaN
1   $215,159,700  $43,031,940        NaN
2   $215,159,700  $43,031,940        NaN
3   $206,794,070  $41,358,814        NaN
4   $205,900,000  $41,180,000        NaN
5   $205,900,000  $41,180,000        NaN
6   $201,158,790  $40,231,758        NaN
7   $197,230,450  $39,446,090        NaN
8   $197,230,450  $39,446,090        NaN
9   $179,299,750  $35,859,950        NaN
10  $177,243,360  $35,448,672        NaN
11  $176,265,152  $44,066,288        NaN
12  $171,131,520  $42,782,880        NaN
13  $163,000,300  $32,600,060        NaN
14  $159,730,592  $39,932,648        NaN
15  $158,253,000  $31,650,600        NaN
16  $152,605,578  $30,521,116        NaN
17  $140,790,600  $35,197,650        NaN
18  $139,888,445  $27,977,689        NaN
19  $136,490,600  $34,122,650        NaN
      Rank                                             Player Signed Age  Yrs  \
286    287  Ramon Sessions  Point Guard | 2012-2013 (FA: 2...         26    2
3585   114  Ersan Ilyasova  Power Forward | 2012-2016 (FA:...         25    5
3287   873  Rayshaun Hammonds  Small Forward | 2020-2020 (...         22    1
1082  1075   Justin Cobbs  Point Guard | 2014-2014 (FA: 2014)         23    1
1969   796  Markel Brown  Shooting Guard | 2017-2017 (FA: ...         25    1
2841   435  Derrick Jones Jr.  Small Forward | 2016-2018 (...         19    3
4716    58         Ian Mahinmi  Center | 2016-2019 (FA: 2020)         29    4
5040   382  Damian Jones  Center | 2016-2019 (FA: 2020)  O...         21    4
2715   309  Joey Graham  Small Forward | 2005-2008 (FA: 20...          -    4
2830   423  Kessler Edwards  Small Forward | 2022-2023 (FA...         21    2
2927   521  Lance Thomas  Small Forward | 2019-2019 (FA: 2...         31    1
5365   707  Khem Birch  Center | 2014-2015 (FA: 2014)  Ori...         21    2
2794   388  Josh Howard  Small Forward | 2003-2006 (FA: 0)...         22    4
4171   701  Norvel Pelle  Power Forward | 2022-2022 (FA: 2...         29    1
696    696  Jarrett Jack  Point Guard | 2016-2016 (FA: 201...         32    1
2389  1217  Steve Kerr  Shooting Guard | 1989-1989 (FA: 19...         23    1
5286   628  Jeff Withey  Center | 2015-2016 (FA: 2017)  Or...         25    2
1625   453  Robert Woodard II  Shooting Guard | 2020-2022 ...         20    3
829    829  Nate Robinson  Point Guard | 2012-2012 (FA: 20...         28    1
3035   622  B.J. Johnson  Small Forward | 2020-2020 (FA: 2...         24    1

            Value          AAV Sign Bonus
286   $10,000,000   $5,000,000        NaN
3585  $40,000,000   $8,000,000        NaN
3287     $898,310     $898,310        NaN
1082     $507,336     $507,336        NaN
1969   $1,471,382   $1,471,382        NaN
2841   $3,401,033   $1,133,678        NaN
4716  $64,000,000  $16,000,000        NaN
5040   $6,334,179   $1,583,545        NaN
2715   $6,926,624   $1,731,656        NaN
2830   $3,565,862   $1,782,931        NaN
2927   $2,320,044   $2,320,044        NaN
5365   $1,352,385     $676,193        NaN
2794   $4,228,523   $1,057,131        NaN
4171   $1,902,133   $1,902,133        NaN
696    $1,551,659   $1,551,659        NaN
2389     $110,000     $110,000        NaN
5286   $1,962,972     $981,486        NaN
1625   $4,800,602   $1,600,201        NaN
829    $1,146,337   $1,146,337        NaN
3035   $1,620,564   $1,620,564        NaN

,Rank,Player,Signed Age,Yrs,Value,AAV,Sign Bonus
5591,933,Boris Diaw Center | 2011-2011 (FA: 2012) Ori...,28,1,"$345,248","$345,248",NaN
5592,934,Ryan Hollins Center | 2015-2015 (FA: 0),31,1,"$344,733","$344,733",NaN
5593,935,Ben Wallace Center | 1997-1997 (FA: 1998) Or...,-,1,"$326,700","$326,700",NaN
5594,936,Joe Kleine Center | 1997-1997 (FA: 1998) Ori...,34,1,"$272,250","$272,250",NaN
5595,937,Jason Collins Center | 2013-2013 (FA: 2014),26,1,"$271,669","$271,669",NaN
5596,938,Ryan Hollins Center | 2011-2011 (FA: 2012) O...,26,1,"$248,048","$248,048",NaN
5597,939,Ben Wallace Center | 1996-1996 (FA: 1997) Or...,-,1,"$247,500","$247,500",NaN
5598,940,Bernard James Center | 2014-2014 (FA: 2015),30,1,"$236,886","$236,886",NaN
5599,941,Larry Sanders Center | 2016-2017 (FA: 2018),28,1,"$207,722","$207,722",NaN
5600,942,Bill Wennington Center | 1993-1993 (FA: 1994)...,29,1,"$150,000","$150,000",NaN
5601,943,Willie Reed Center | 2013-2014 (FA: 2015) Or...,23,1,"$102,089","$102,089",NaN
5602,944,Dan Gadzuric Center | 2011-2011 (FA: 2012) O...,34,1,"$69,393","$69,393",NaN
5603,945,Isaac Humphries Center | 2018-2018 (FA: 2019)...,21,1,"$47,371","$47,371",NaN
5604,946,Henry Sims Center | 2015-2015 (FA: 2016) Ori...,26,1,"$46,181","$46,181",NaN
5605,947,Hilton Armstrong Center | 2013-2013 (FA: 2014),28,1,"$42,306","$42,306",NaN
5606,948,Dexter Pittman Center | 2013-2013 (FA: 2014) ...,24,1,"$37,722","$37,722",NaN
5607,949,Prince Ibeh Center | 2016-2016 (FA: 2017),22,1,"$28,772","$28,772",NaN
5608,950,Christian Wood Center | 2015-2015 (FA: 2016) ...,20,1,"$21,621","$21,621",NaN
5609,951,Greg Stiemsma Center | 2009-2009 (FA: 2010) ...,23,1,"$5,572","$5,572",NaN
5610,952,Jeff Foster Center | 1999-2002 (FA: 2003),-,4,$4,$1,NaN

In [ ]:
# look at the shape of the salary dataset
print("shape of df_sal dataframe: ", df_sal.shape, end="\n\n")

# look at data types and also determine existance of any NaN values in all the columns
for column in df_sal.columns:
    print(
        column,
        "- ",
        "Type: ",
        df_sal[column].dtypes,
        ", NaN Value: ",
        df_sal[column].isnull().any(),
    )

shape of df_sal dataframe:  (5611, 7)

Rank -  Type:  int64 , NaN Value:  False
Player -  Type:  object , NaN Value:  False
Signed Age -  Type:  object , NaN Value:  False
Yrs -  Type:  int64 , NaN Value:  False
Value -  Type:  object , NaN Value:  False
AAV -  Type:  object , NaN Value:  False
Sign Bonus -  Type:  object , NaN Value:  True

In [ ]:
# make copy of dataset for safety
df_salary = df_sal.copy()

In [ ]:
#check 'Player' column in df_salary
df_salary["Player"]

0       Stephen Curry  Point Guard | 2022-2025 (FA: 2026)
1         Luka Doncic  Point Guard | 2022-2026 (FA: 2027)
2          Trae Young  Point Guard | 2022-2026 (FA: 2027)
3       Russell Westbrook  Point Guard | 2018-2022 (FA...
4         LaMelo Ball  Point Guard | 2024-2028 (FA: 2029)
                              ...
5606    Dexter Pittman  Center | 2013-2013 (FA: 2014) ...
5607           Prince Ibeh  Center | 2016-2016 (FA: 2017)
5608    Christian Wood  Center | 2015-2015 (FA: 2016) ...
5609    Greg Stiemsma  Center | 2009-2009 (FA: 2010)  ...
5610           Jeff Foster  Center | 1999-2002 (FA: 2003)
Name: Player, Length: 5611, dtype: object

As we observe the data in the 'Player' column above, it contains information about the player's name, position, contract start year, contract end year, and free agent year. We will extract each of these data from the 'Player' column and allocate them to new columns.

In [ ]:
# extract data from the Player column and assign them to two new columns: names & positions
split_name_yr = df_salary["Player"].str.split("|")

name_position = split_name_yr.apply(lambda x: x[0])

names = name_position.str.split("  ").apply(lambda x: x[0])
positions = name_position.str.split("  ").apply(lambda x: x[1].strip())

print(names[names == 'J.J. Redick'].head(1))
print(names[names == 'Gary Trent Jr.'].head(1))
print(names[names == 'Joe Ingles'].head(1))
print(names[names == 'Frank Mason III'].head(1))

# eliminate special characters in dataframe column names
def clean_player_names(df, suffixes_to_remove):
    """The purpose of this function is to eliminate 
    the special characters in the names column.
    
    It accepts the following parameters:
        1) the dataframe to be cleaned
        2) a list of special characters to be removed
    """
    for suffix in suffixes_to_remove:
        df = df.str.replace(suffix, "", regex=True)
    return df

suffixes_to_remove = ["\."," Jr"," Sr"," III"," II"," IV"]
names = clean_player_names(names, suffixes_to_remove)

1309    J.J. Redick
Name: Player, dtype: object
1248    Gary Trent Jr.
Name: Player, dtype: object
2469    Joe Ingles
Name: Player, dtype: object
431    Frank Mason III
Name: Player, dtype: object

In [ ]:
# eliminate middle names and assign player positions to a new column called Positions
first_name = names.str.split(" ").apply(lambda x: x[0].strip())
last_name = names.str.split(" ").apply(lambda x: x[-1].strip())

df_salary["Names"] = first_name + " " + last_name
df_salary["Positions"] = positions

In [ ]:
# check if '.' and 'Jr' in Names column still exists
print(df_salary['Names'][df_salary['Names'] == "JJ Redick"])
print(df_salary['Names'][df_salary['Names'] == "Gary Trent"])

1309    JJ Redick
1316    JJ Redick
1333    JJ Redick
1354    JJ Redick
1431    JJ Redick
1506    JJ Redick
Name: Names, dtype: object
1248    Gary Trent
1668    Gary Trent
Name: Names, dtype: object

In [ ]:
# extract contract start year, end year, freeagent year data from the Player column and assign them to new columns
start_end_freeagent_yr = split_name_yr.apply(lambda x: x[1])
str_end_free = start_end_freeagent_yr.str.extract(
    "(?P<Start_Year>[\d]*)\-(?P<End_Year>[\d]*)\s\(FA:\s(?P<FreeAgent_Year>.*)\)"
)

# combine str_end_free and df_salary dataframes
df_salary = pd.concat([df_salary, str_end_free], axis=1)
df_salary.head()

,Rank,Player,Signed Age,Yrs,Value,AAV,Sign Bonus,Names,Positions,Start_Year,End_Year,FreeAgent_Year
0,1,Stephen Curry Point Guard | 2022-2025 (FA: 2026),33,4,"$215,353,664","$53,838,416",NaN,Stephen Curry,Point Guard,2022,2025,2026
1,2,Luka Doncic Point Guard | 2022-2026 (FA: 2027),22,5,"$215,159,700","$43,031,940",NaN,Luka Doncic,Point Guard,2022,2026,2027
2,2,Trae Young Point Guard | 2022-2026 (FA: 2027),22,5,"$215,159,700","$43,031,940",NaN,Trae Young,Point Guard,2022,2026,2027
3,4,Russell Westbrook Point Guard | 2018-2022 (FA...,28,5,"$206,794,070","$41,358,814",NaN,Russell Westbrook,Point Guard,2018,2022,2023
4,5,LaMelo Ball Point Guard | 2024-2028 (FA: 2029),21,5,"$205,900,000","$41,180,000",NaN,LaMelo Ball,Point Guard,2024,2028,2029

Next, we will proceed to fill the NaN values in the "Sign Bonus" column with '0'. We will then create a function to clean the salary columns (AVV, Value, Sign Bonus) by removing dollar signs and converting their data types to integers.

In [ ]:
# fill NaN values with '0' for Sign Bonus column
df_salary["Sign Bonus"] = df_salary["Sign Bonus"].fillna("0")

In [ ]:
# Create a function to transform string values with dollar sign as numeric integer
def extract_and_clean_numeric(value):
    cleaned_values = value.str.replace("[\$,]", "", regex=True)
    return cleaned_values.astype(int)

In [ ]:
# Create a function create new columns to be assigned with data transformed from extract_and_clean_numeric function
def clean_columns(df, column_lst):
    for i in column_lst:
        df[i + "Clean"] = extract_and_clean_numeric(df[i])

In [ ]:
# extract and clean target columns into numeric
clean_columns(df_salary, ["AAV", "Value", "Sign Bonus"])
df_salary.head()

,Rank,Player,Signed Age,Yrs,Value,AAV,Sign Bonus,Names,Positions,Start_Year,End_Year,FreeAgent_Year,AAVClean,ValueClean,Sign BonusClean
0,1,Stephen Curry Point Guard | 2022-2025 (FA: 2026),33,4,"$215,353,664","$53,838,416",0,Stephen Curry,Point Guard,2022,2025,2026,53838416,215353664,0
1,2,Luka Doncic Point Guard | 2022-2026 (FA: 2027),22,5,"$215,159,700","$43,031,940",0,Luka Doncic,Point Guard,2022,2026,2027,43031940,215159700,0
2,2,Trae Young Point Guard | 2022-2026 (FA: 2027),22,5,"$215,159,700","$43,031,940",0,Trae Young,Point Guard,2022,2026,2027,43031940,215159700,0
3,4,Russell Westbrook Point Guard | 2018-2022 (FA...,28,5,"$206,794,070","$41,358,814",0,Russell Westbrook,Point Guard,2018,2022,2023,41358814,206794070,0
4,5,LaMelo Ball Point Guard | 2024-2028 (FA: 2029),21,5,"$205,900,000","$41,180,000",0,LaMelo Ball,Point Guard,2024,2028,2029,41180000,205900000,0

Let's determine the number of players who have received bonuses. We will then add these bonuses to the total salary and distribute them evenly over the duration of their respective contracts, thereby calculating the annual bonus contribution to their salaries.

In [ ]:
# totally 18 rows with sign bonus
df_salary[['Names','Sign BonusClean']][df_salary["Sign Bonus"] != "0"]

                    Names  Sign BonusClean
185          Jarrett Jack          3500000
1235        Malik Beasley           300000
1289      Wesley Matthews          5690000
1354            JJ Redick           500000
1565       Michael Jordan           250000
1689         Zoran Dragic           412500
2432         Jimmy Butler          4600000
2483        Nicolas Batum          1500000
2670  Kostas Papanikolaou           206598
3564          John Henson          4000000
3639         Paul Millsap          5600000
3651       Jared Jeffries          6049000
3693            Luc Moute          1705923
3725         Brandon Bass          2000000
3789       Furkan Aldemir           305854
3795        Nick Collison          6500000
3851        Joel Freeland          1338000
3977         Gustavo Ayon            67500

In [ ]:
# add bonus on total salary and allocate bonus to each year's salary
df_salary["AAV+Bonus"] = (
    df_salary["Sign BonusClean"] / df_salary["Yrs"] + df_salary["AAVClean"]
)
df_salary["Value+Bonus"] = df_salary["Sign BonusClean"] + df_salary["ValueClean"]

Next let's check the 'Yrs', 'Start_Year', 'End_Year', 'FreeAgent_Year' columns.

In [ ]:
print('Any Zero values for Yrs: ', (df_salary["Yrs"] == 0).any())
print('NaN values for Yrs: ', df_salary["Yrs"].isna().any())

Any Zero values for Yrs:  False
NaN values for Yrs:  False

There are no 0 or NaN values in contract year column(Yrs). Let's explore the data in 'Start_Year', 'End_Year', 'FreeAgent_Year' columns

In [ ]:
# convert data type from string to int
df_salary[["Start_Year", "End_Year", "FreeAgent_Year"]] = df_salary[
    ["Start_Year", "End_Year", "FreeAgent_Year"]
].astype(int)

print('shape if any zero values for Start_Year, End_Year, and FreeAgent_Year: ',
    df_salary[
        (df_salary["Start_Year"] == 0)
        | (df_salary["End_Year"] == 0)
        | (df_salary["FreeAgent_Year"] == 0)
    ].shape
)

print('shape of all Start_Year, End_Year, and FreeAgent_Year are zero: ',
    df_salary[
        (df_salary["Start_Year"] == 0)
        & (df_salary["End_Year"] == 0)
        & (df_salary["FreeAgent_Year"] == 0)
    ].shape
)

print(
    df_salary[
        (df_salary["Start_Year"] == 0)
        & (df_salary["End_Year"] == 0)
        & (df_salary["FreeAgent_Year"] == 0)
    ]
)

shape if any zero values for Start_Year, End_Year, and FreeAgent_Year:  (336, 17)
shape of all Start_Year, End_Year, and FreeAgent_Year are zero:  (2, 17)
      Rank                                Player Signed Age  Yrs       Value  \
5010   352    Robert Swift  Center | 0-0 (FA: 0)         -1    4  $7,894,553
5535   875  Jaleel Roberts  Center | 0-0 (FA: 0)         23    1    $543,471

             AAV Sign Bonus           Names Positions  Start_Year  End_Year  \
5010  $1,973,638          0    Robert Swift    Center           0         0
5535    $543,471          0  Jaleel Roberts    Center           0         0

      FreeAgent_Year  AAVClean  ValueClean  Sign BonusClean  AAV+Bonus  \
5010               0   1973638     7894553                0  1973638.0
5535               0    543471      543471                0   543471.0

      Value+Bonus
5010      7894553
5535       543471

It has been identified that 336 rows contain 0 values in either the 'startYear,' 'endYear,' or 'freeAgentYear' columns, and there are 2 rows where all these columns have values of 0. We will create a function to perform data cleaning and populate the appropriate values in these columns.

In [ ]:
# Create a function to populate the appropriate values in these columns: Start_Year, End_Year, FreeAgent_Year 
# We do not perform manipulation when all three variables are 0 or when all three variables are not 0

def fill_value(row):
    '''The purpose of this function is to fill in most of the Start_Year, End_Year, FreeAgent_Year
    that are 0 values'''
    if row["Start_Year"] == 0 and row["End_Year"] == 0 and row["FreeAgent_Year"] != 0:
        row["End_Year"] = row["FreeAgent_Year"] - 1
        row["Start_Year"] = row["End_Year"] - row["Yrs"] + 1
    if row["Start_Year"] == 0 and row["End_Year"] != 0 and row["FreeAgent_Year"] != 0:
        row["Start_Year"] = row["End_Year"] - row["Yrs"] + 1
    if row["Start_Year"] != 0 and row["End_Year"] == 0 and row["FreeAgent_Year"] != 0:
        row["End_Year"] = row["Start_Year"] + row["Yrs"] - 1
    if row["Start_Year"] != 0 and row["End_Year"] == 0 and row["FreeAgent_Year"] == 0:
        row["End_Year"] = row["Start_Year"] + row["Yrs"] - 1
        row["FreeAgent_Year"] = row["End_Year"] + 1
    if row["Start_Year"] == 0 and row["End_Year"] != 0 and row["FreeAgent_Year"] == 0:
        row["Start_Year"] = row["End_Year"] - row["Yrs"] + 1
        row["FreeAgent_Year"] = row["End_Year"] + 1
    if row["Start_Year"] != 0 and row["End_Year"] != 0 and row["FreeAgent_Year"] == 0:
        row["FreeAgent_Year"] = row["End_Year"] + 1
    return row

#apply fill in function for Start_Year, End_Year, FreeAgent_Year to the df_salary dataframe 
df_salary = df_salary.apply(fill_value, axis=1)

Next, we will address the missing values in the "Start_Year," "End_Year," and "FreeAgent_Year" columns. However, it's important to note that we encountered significant inaccuracies in Robert Swift's data within our dataset, making it challenging to rectify. Additionally, we discovered that Jaleel Roberts is a G-League player rather than an NBA player. Consequently, we have made the decision to remove these two data points from our dataset.

In [ ]:
# check Robert Swift and Jaleel Roberts data rows
df_salary[
        (df_salary["Start_Year"] == 0)
        & (df_salary["End_Year"] == 0)
        & (df_salary["FreeAgent_Year"] == 0)
    ]

,Rank,Player,Signed Age,Yrs,Value,AAV,Sign Bonus,Names,Positions,Start_Year,End_Year,FreeAgent_Year,AAVClean,ValueClean,Sign BonusClean,AAV+Bonus,Value+Bonus
5010,352,Robert Swift Center | 0-0 (FA: 0),-1,4,"$7,894,553","$1,973,638",0,Robert Swift,Center,0,0,0,1973638,7894553,0,1973638.0,7894553
5535,875,Jaleel Roberts Center | 0-0 (FA: 0),23,1,"$543,471","$543,471",0,Jaleel Roberts,Center,0,0,0,543471,543471,0,543471.0,543471

In [ ]:
# drop Robert Swift and Jaleel Roberts data rows
df_salary.drop(
    df_salary[
        (df_salary["Start_Year"] == 0)
        & (df_salary["End_Year"] == 0)
        & (df_salary["FreeAgent_Year"] == 0)
    ].index,
    inplace=True
)

In [ ]:
#function for checking the string length of year
def check_year_length(specific_year):
    '''The purpose of this function is to check if there are any years less than 4 numbers'''
    if len(str(specific_year)) < 4:
        return specific_year
    else:
        return np.nan

#check any year that is incorrectly not a length of 4 numbers
for year in ["Start_Year", "End_Year", "FreeAgent_Year"]:
    series_year_not_accurate = df_salary[year].apply(check_year_length)
    year_index = series_year_not_accurate[series_year_not_accurate.isnull() == False].index
    print(df_salary['Names'].loc[year_index])
    print(series_year_not_accurate[series_year_not_accurate.isnull() == False])

Series([], Name: Names, dtype: object)
Series([], Name: Start_Year, dtype: float64)
593    Raul Neto
Name: Names, dtype: object
593    202.0
Name: End_Year, dtype: float64
4545     Jameel Warney
5201    DeAndre Jordan
Name: Names, dtype: object
4545     20.0
5201    202.0
Name: FreeAgent_Year, dtype: float64

We can notice from the above output that the following 3 players (Raul Neto, Jameel Warney and DeAndre Jordan) have incorrect length of either End_Year or FreeAgent_Year variables.

In [ ]:
#check the 3 names that have incorrect End_Year and FreeAgent_Year so we can fill in
print(df_salary[["Names", "Start_Year", "End_Year", "FreeAgent_Year", "AAV", "Value"]][df_salary["Names"] == "Raul Neto"])
print(df_salary[["Names", "Start_Year", "End_Year", "FreeAgent_Year", "AAV", "Value"]][df_salary["Names"] == "Jameel Warney"])
print(df_salary[["Names", "Start_Year", "End_Year", "FreeAgent_Year", "AAV", "Value"]][df_salary["Names"] == "DeAndre Jordan"])

         Names  Start_Year  End_Year  FreeAgent_Year         AAV       Value
414  Raul Neto        2018      2019            2020  $2,200,000  $4,400,000
499  Raul Neto        2015      2017            2018    $910,849  $2,732,546
528  Raul Neto        2022      2022            2023  $2,463,490  $2,463,490
593  Raul Neto        2021       202            2022  $2,089,448  $2,089,448
618  Raul Neto        2020      2020            2021  $1,882,867  $1,882,867
646  Raul Neto        2019      2019            2020  $1,737,145  $1,737,145
              Names  Start_Year  End_Year  FreeAgent_Year       AAV     Value
4501  Jameel Warney        2017      2017            2018  $815,615  $815,615
4545  Jameel Warney        2016      2016              20  $543,471  $543,471
               Names  Start_Year  End_Year  FreeAgent_Year          AAV  \
4690  DeAndre Jordan        2015      2018            2019  $21,904,013
4773  DeAndre Jordan        2011      2014            2015  $10,759,764
4783  DeAndre Jordan        2019      2022            2023   $9,990,179
4838  DeAndre Jordan        2018      2018            2019  $22,897,200
5161  DeAndre Jordan        2023      2023            2024   $3,196,448
5181  DeAndre Jordan        2022      2022            2023   $2,905,851
5201  DeAndre Jordan        2021      2021             202   $2,641,691
5261  DeAndre Jordan        2008      2010            2011     $713,603

            Value
4690  $87,616,050
4773  $43,039,054
4783  $39,960,716
4838  $22,897,200
5161   $3,196,448
5181   $2,905,851
5201   $2,641,691
5261   $2,140,809

In [ ]:
#fill in incorrect year value
df_salary.at[593,'End_Year'] = 2021
df_salary.at[4545, 'FreeAgent_Year'] = 2017
df_salary.at[5201, 'FreeAgent_Year'] = 2022

Next, we will create a 'Year_List' column. Our goal is to expand the data in this 'Year_List' by breaking down contracts spanning multiple years into individual yearly contracts. This will facilitate the merging of the player statistic and salary dataframe on season years.

In [ ]:
# make the year_list so we can explode it 
start_years = df_salary["Start_Year"].values
end_years = df_salary["End_Year"].values
df_salary["Year_List"] = [
    np.arange(start, end + 1) for start, end in zip(start_years, end_years)
]

In [ ]:
#explode the Year_List column for each row to include each year of the contract
df_salary_exploded = df_salary.explode("Year_List")

In [ ]:
# check any 0 value in column Year_List
df_salary_exploded[df_salary_exploded["Year_List"] == 0]

Empty DataFrame
Columns: [Rank, Player, Signed Age, Yrs, Value, AAV, Sign Bonus, Names, Positions, Start_Year, End_Year, FreeAgent_Year, AAVClean, ValueClean, Sign BonusClean, AAV+Bonus, Value+Bonus, Year_List]
Index: []

In [ ]:
# check any nan value in column Year_List
df_salary_exploded[df_salary_exploded["Year_List"].isna()]

Empty DataFrame
Columns: [Rank, Player, Signed Age, Yrs, Value, AAV, Sign Bonus, Names, Positions, Start_Year, End_Year, FreeAgent_Year, AAVClean, ValueClean, Sign BonusClean, AAV+Bonus, Value+Bonus, Year_List]
Index: []

We have now successfully manipulated and cleaned the year columns. The next step involves merging the salary data (df_salary_exploded) and the statistics data (player_statistics_country) based on player names and years. However, before proceeding with the merge, it is essential to check for any discrepancies or mismatches between the player names in the two datasets.

In [ ]:
names_set1 = set(df_salary_exploded['Names'])
names_set2 = set(player_statistics_country['PLAYER_NAME'])

# Players present in the first dataset but not in the second dataset
in_df1_not_in_df2 = names_set1 - names_set2

# Players present in the second dataset but not in the first dataset
in_df2_not_in_df1 = names_set2 - names_set1

# Print the discrepancies
print("Players in salary but not in stats:")
print(in_df1_not_in_df2)

print("\nPlayers in stats but not in salary:")
print(in_df2_not_in_df1)

Players in salary but not in stats:
{'Ben Sheppard', 'Melo Trimble', 'Christian Watford', 'Jordan Henriquez', 'Mark Ogden', 'Shawn Dawson', 'Brady Heslip', 'Shizz Alston', 'BJ Young', 'Matthew Hurt', 'Bryce Hamilton', 'Robert Vaden', 'Brock Motum', "Hamady N'Diaye", 'Paul Eboua', 'Rick Jackson', 'Matur Maker', 'Max Heidegger', 'Jeff Taylor', 'Michael Eric', 'Nikola Jovanovic', 'Brandon Rachal', 'Nate Sestina', 'Christian Vital', 'Kyle Casey', 'Mustapha Farrakhan', 'Fuquan Edwin', 'Rayan Rupert', 'Vashil Fernandez', 'Dmytro Skapintsev', 'Kleon Penn', 'George Conditt', 'Stefhon Hannah', 'Jordan Vandenberg', 'Aamir Simms', 'Shawn Jones', 'Sheldon McClellan', 'Edgar Sosa', 'Tony Gaffney', 'Jordan Railey', 'Eric Griffin', 'Jake Anderson', 'Goran Suton', 'Darryl Morsell', 'Zach Smith', 'Joseph Young', 'Ronald Roberts', 'Bilal Coulibaly', 'DeJaun Blair', 'Alex Antetokounmpo', "Maurice N'dour", 'Quinton Rose', 'Jacob Toppin', 'CJ Aiken', 'Oscar Bellfield', 'Matt Janning', 'Dan Nwaelele', 'Trevon Scott', 'Tomislav Zubcic', 'LJ Figueroa', 'Remi Yusuf', 'Greg Somogyi', 'John Petty', 'Maxwell Lewis', 'Michael Qualls', 'Marshall Henderson', 'Kenny Gabriel', 'Jeremy Senglin', 'Romaro Gill', 'Kenny Wooten', 'Trey Lewis', 'Carleton Scott', 'Devonte Patterson', 'Ishmael Smith', "Sir'Dominic Pointer", 'Phil Jones', 'Erik Atkins', 'Andrew Andrews', 'Akil Mitchell', 'Devin Sweetney', 'Luigi Datome', 'Jeffrey Carroll', 'Stanley Robinson', 'Deshaun Thomas', 'Stephen Dennis', 'Julian Strawther', 'Chad Brown', 'Pete Nance', 'Nene Hilario', 'LiAngelo Ball', 'Dedric Lawson', 'Nate Renfro', 'Ismaila Kane', 'Jakeenan Gant', 'Ethan Thompson', 'Kellan Grady', 'Jaleel Cousins', 'Damion Baugh', 'David Lighty', 'Louis Williams', 'Jalen Adams', 'Luke Hancock', 'CJ Fair', 'Mouhamed Gueye', 'Chris Walker', 'Anthony Duruji', 'Toure Murry', 'Abdul Gaddy', 'Justin Simon', 'Nicholas King', 'Thomas Walkup', 'Herb Jones', 'Larry Bird', "D'Aundray Brown", 'TJ Williams', 'Marcus Sasser', 'Khalif Wyatt', 'Wesley Witherspoon', 'Mirza Begic', 'Joe Jackson', 'Isaiah Pineiro', 'Eric Boateng', 'Brandon McCoy', 'Magnum Rolle', 'Mitchell Watt', 'Keandre Cook', 'Dariq Whitehead', 'Charlie Westbrook', 'Aaron Craft', 'Anthony Tarke', 'Juwan Staten', 'Victor Wembanyama', 'Jeriah Horne', 'Joel Berry', 'Ibou Badji', 'Jules Bernard', 'Matt Farrell', 'Christapher Johnson', 'Roy Marble', 'Richard Solomon', 'Bronson Koenig', 'Angel Rodriguez', 'Prince Ibeh', 'Jaron Johnson', 'Aric Holman', 'Walter Tavares', 'Romeo Weems', 'John Egbunu', 'Bryson Williams', 'Luke Maye', 'Brandin Podziemski', 'Matthew Mayer', 'Breein Tyree', 'Alex Robinson', 'Kennedy Meeks', 'Darion Atkins', 'Ryan Boatright', 'Marcus Simmons', 'Arsalan Kazemi', 'Michale Kyser', 'Iverson Molinar', 'Trey Freeman', 'Levi Randolph', 'Brian Butch', "Da'Sean Butler", 'Jarrid Famous', 'James Akinjo', 'Justin Cobbs', 'Alec Brown', 'Carlos Morais', 'Jahlil Tripp', 'John Bohannon', 'Lance Goulbourne', 'Mac Koshwal', 'Jermaine Samuels', 'Christ Koumadje', 'Marcus Bingham', 'Andrew Funk', 'Filip Petrusev', 'Justin Tillman', 'Tosan Evbuomwan', 'Marcus Foster', 'Tu Holloway', 'Quincy Ford', 'Leonard Miller', 'Kenny Kadji', 'Nate Pierre-Louis', 'Damen Bell-Holter', 'Scoot Henderson', 'Nick Zeisloft', 'Jamar Smith', 'Courtney Fells', 'Nick Minnerath', 'Jaime Echenique', 'Colby Jones', 'Ryan Richards', 'Marcus Zegarowski', 'Scottie Wilbekin', 'Cameron Jones', 'Joshua Smith', 'Nick Wiggins', 'Scottie Lindsey', 'DJ Steward', 'Kenny Hasbrouck', 'Corey Webster', 'Charles Matthews', 'Tres Tinkle', 'JP Tokoto', 'Tidjan Keita', 'Lamar Peters', 'Bo McCalebb', 'Oleksandr Kobets', 'Corey Hawkins', 'Sagaba Konate', 'Drake Jeffries', 'Marcus Lee', 'Keyonte George', 'Olivier Hanlan', 'Johnny Hamilton', 'Robert Johnson', 'Michael Lee', 'Ryan Allen', 'Rasheed Sulaimon', 'Kadeem Jack', 'Kobe Brown', 'EJ Liddell', 'Ding Yanyuhang', 'Elijah Pemberton', 'Ibi Watson', 'Trevon Bluiett', 'Mitch Ballock', 'Chris Udofia', 'Caleb Homesley', 'Gracin Bakumanya', 'Mamadou N’Diaye', 'Sidy Cissoko', 'Malcom Delaney', 'Stephen Holt', 'Jordan Ford', 'Chris Daniels', 'Brice Sensabaugh', 'William McDowell-White', 'Jordan Hawkins', 'Bryce Brown', 'Jamorio Moon', 'Dereck Lively', 'Kadeem Batts', 'Travis Trice', 'Reginald Becton', 'Lazeric Jones', 'Trent Plaisted', 'Richard Howell', 'Jalen Hood-Schifino', 'Barry Brown', 'Seth Tarver', 'Tony Carr', 'Makur Maker', 'Kahlil Whitney', 'Jeremiah Tilmon', 'Derek Culver', 'Carlon Brown', 'Bennie Boatwright', 'Toumani Camara', 'Egidijus Mockevicius', 'Kyle Fogg', 'Michael Holyfield', 'EJ Singler', 'Marial Shayock', 'CJ Massinburg', 'Devontae Shuler', 'Jordan Mathews', 'Keith Hornsby', 'Tiwian Kendley', 'Kaiser Gates', 'Ishmail Wainright', 'Nick Smith', 'Noah Clowney', 'Stefan Jankovic', 'Julian Phillips', 'Sam Thompson', 'Jarace Walker', 'Yanick Moreira', 'Cameron Thomas', 'Micah Downs', 'Dakarai Allen', 'BJ Taylor', 'Chris Livingston', 'Roscoe Smith', 'Markel Crawford', 'Myck Kabongo', 'Kaleb Tarczewski', 'Sviatoslav Mykhailiuk', 'Jaleel Roberts', 'Tyus Battle', 'John Shurna', 'Rade Zagorac', 'Will Cummings', 'DJ Hogg', 'Brian Qvale', 'Denzel Mahoney', 'Romero Osby', 'Wesley Saunders', 'Rodney Williams', 'George Paula', 'Desi Rodriguez', 'Jordan Bachynski', 'Grant Golden', 'Orlando Sanchez', 'Jose Barea', 'Nuni Omot', 'David Kramer', 'Wesley Iwundu', 'Doral Moore', 'DJ Stewart', 'Terry Larrier', 'Jon Davis', 'Steven Gray', 'Tre Kelley', 'Talib Zanna', 'Vasilije Micic', 'Amen Thompson', 'Jermey Pargo', 'Louis Amundson', 'Henri Drell', 'LJ Peak', 'Malik Ellison', 'Scott Wood', 'Sun Yue', 'Kobe Bufkin', 'Chet Holmgren', 'Marcus Denmon', 'AJ Reeves', 'Rayshaun Hammonds', 'Gabe Brown', 'Isaac Hamilton', 'Sampson Carter', 'LaVoy Allen', 'James Banks', 'Olivier-Maxence Prosper', 'Beau Beech', 'Richard McConnell', 'Damien Jefferson', 'Dallas Lauderdale', 'Sacha Killeya-Jones', 'Jaylen Barford', 'Terran Petteway', 'Jonathan Holmes', 'Cason Wallace', 'Dee Bost', 'Shannon Scott', 'Michael Dunigan', 'Isaiah Cousins', 'Yoeli Childs', 'Trayce Jackson-Davis', "Nah'Shon Hyland", 'Vince Hunter', 'Peter Jok', 'Landry Nnoko', 'Justin Powell', 'Reeves Nelson', 'DJ Carton', 'Brandon Heath', 'Kaleb Wesson', 'Casey Prather', 'Brandon Miller', 'Mohamed Bamba', 'Justin Smith', 'Marqus Blakely', 'Luca Vildoza', 'Josh Bostic', 'Elijah Stewart', 'Drew Crawford', 'Raef Lafrentz', 'Robert Upshaw', 'Luke Nevill', 'Devin Searcy', 'Vyacheslav Kravtsov', 'Terry Henderson', 'Sergey Gladyr', 'Anthony Black', 'Vince Edwards', 'Jaylen Johnson', 'Ronnie Aguilar', 'Isaac Haas', 'Dennis Schröder', 'Trent Lockett', 'Jordan Walsh', 'Olek Czyz', 'Jake Toolson', 'Terrico White', 'Nick Ongenda', 'Justin Brownlee', 'Ronshad Shabazz', 'Jordan Barnett', 'MaCio Teague', 'Jason Washburn', 'Mailk Hairston', 'VJ Beachem', 'Simisola Shittu', 'Magic Johnson', 'Canyon Barry', 'Kenny Williams', 'Patric Young', 'Jordan Murphy', 'Dikembe Dixson', 'Troy Baxter', 'James Mays', 'Jae’Sean Tate', 'Jon Horford', 'DeShawn Sims', 'Denzel Livingston', 'Dez Wells', 'Kamari Murphy', 'Giorgi Bezhanishvili', 'Jaime Jaquez', 'Gradey Dick', 'Michael Cobbins', 'Sedrick Barefield', 'Jordan Burns', 'Josh Owens', 'Rashawn Thomas', 'Devin Williams', 'Corey Walden', 'Jonathan Stark', 'Jett Howard', 'Hunter Tyson', 'Kammron Taylor', "D'or Fischer", 'EJ Montgomery', 'VJ King', 'Élie Okobo', 'Phil Carr', 'James Blackmon', 'Zak Irvin', 'Galen Robinson', 'Walter Lemon', 'Garrison Brooks', 'Zach Auguste', 'Robert Dozier', 'Kris Murray', 'Yudai Baba', 'Perry Ellis', 'Michael Devoe', 'Demonte Harper', 'Nicolas Claxton', 'CJ Leslie', 'Elgin Cook', 'Cam Whitmore', 'Taylor Hendricks', 'Nnanna Egwu', 'Andre Jackson', 'Youssou Ndoye', 'Hank Thorns', 'Yuki Togashi', 'Brandon Ashley', 'Davion Mintz', 'Trevion Williams', 'Yannis Morin', 'Melvin Ejim', 'Jalen Pickett', 'Rob Gray', 'BJ Mullens', 'Anthony Lawrence', 'Reginald Kissoonlal', 'Taylor Funk', 'Sasha Vezenkov', 'Livio Jean-Charles', 'Garrett Siler', 'Ron Howard', 'Diamon Simpson', 'Brandon Dawson'}

Players in stats but not in salary:

In [ ]:
len(in_df1_not_in_df2)

471

We expect the salary dataset to be incomplete and to not have values seen in the statistics dataset from nba.com because sportrac only contains at most the top 2000 salaries for each position and is not the official basketball website. It is therefore prudent to ignore player names in statistics dataset that are not in salary (in_df2_not_in_df1). On the other hand, we expect most of the players in the salary dataset to be in the statistics nba.com dataset since it is their official website and should be complete. So it is surprising that there are so many names in the salary dataset that are not in the nba.com dataset (in_df1_not_in_df2). We will have to investigate further by looking at individual instances of the players' profiles to determine why those names are not in the nba.com website. To do so, lets first save the missing_names to a csv and then research.

In [ ]:
missing_names = pd.DataFrame(in_df1_not_in_df2, columns = ['missing_names']).sort_values(by = 'missing_names').to_csv('Name_Mismatch.csv', index = False)

After researching through wikipedia.com and the statistics page on nba.com, we have found the reasons for all the missing data in the missing_names.csv file created above. We noticed that there is either: a) a mismatch in the names between salary and statistics dataframes or b) they never played a regular NBA game yet even though they may have salary contracts. We updated the missing_names.csv file with a 'mismatch' and 'reason' columns corresponding to the aforementioned reasons and will now upload the newly created missing_names_filled.csv file.

In [ ]:
#read filled out names with 'mismatch' or an alternate 'reason' on salary dataset
name_mismatch_filled = pd.read_csv('Name_Mismatch_Filled.csv')

name_mismatch_filled.head()

           names mismatch    reason
0      AJ Reeves      NaN  G-league
1    Aamir Simms      NaN       LBA
2    Aaron Craft      NaN  G-league
3    Abdul Gaddy      NaN  G-league
4  Akil Mitchell      NaN  G-league

In [ ]:
#see all the names that had mismatches
name_fix = name_mismatch_filled[name_mismatch_filled['reason'].isnull()][['names','mismatch']]
name_fix

                     names             mismatch
31          Brandon Dawson       Branden Dawson
52          Cameron Thomas           Cam Thomas
68     Christapher Johnson        Chris Johnson
95            DeJaun Blair         DeJuan Blair
100        Dennis Schröder      Dennis Schroder
136          Garrett Siler         Garret Siler
146         Hamady N'Diaye        Hamady Ndiaye
149             Herb Jones        Herbert Jones
157          Ishmael Smith            Ish Smith
158      Ishmail Wainright        Ish Wainright
163          Jae’Sean Tate        Jae'Sean Tate
172            Jalen Adams         Jaylen Adams
180           Jamorio Moon         Jamario Moon
187            Jeff Taylor       Jeffery Taylor
193           Jermey Pargo         Jeremy Pargo
202              Jon Davis         Johnny Davis
217             Jose Barea             JJ Barea
218           Joseph Young            Joe Young
221           Joshua Smith           Josh Smith
259            LaVoy Allen          Lavoy Allen
269         Louis Amundson         Lou Amundson
270         Louis Williams         Lou Williams
272           Luigi Datome          Gigi Datome
280         Mailk Hairston       Malik Hairston
282         Malcom Delaney      Malcolm Delaney
292         Marial Shayock        Marial Shayok
319          Mohamed Bamba             Mo Bamba
322        Nah'Shon Hyland         Bones Hyland
327           Nene Hilario            Nene Nene
334        Nicolas Claxton          Nic Claxton
356          Raef Lafrentz        Raef LaFrentz
402      Sheldon McClellan          Sheldon Mac
413                Sun Yue              Sun Sun
414  Sviatoslav Mykhailiuk       Svi Mykhailiuk
431            Toure Murry         Toure' Murry
440           Trevon Scott            Tre Scott
451          Vince Edwards      Vincent Edwards
452           Vince Hunter       Vincent Hunter
453    Vyacheslav Kravtsov  Viacheslav Kravtsov
454           Wade Baldwin         Wade Baldwin
455           Walter Lemon           Walt Lemon
456         Walter Tavares          Edy Tavares
457          Wesley Iwundu           Wes Iwundu
471             Élie Okobo           Elie Okobo

In [ ]:
#check all the mismatch names are accounted for in the statistics dataframe
mismatch_names = set(name_fix['mismatch'])
names_in_stats = set(player_statistics_country['PLAYER_NAME'])
mismatch_names-names_in_stats

set()

We have identified all the mismatched names, and our next step is to replace these mismatched names in the salary data with the official NBA player names

In [ ]:
#make a dictionary of names and their replacements
name_to_replace_dict = dict(zip(name_fix['names'], name_fix['mismatch']))

#replace mismatched names of salary dataset with the official NBA player name
df_salary_exploded['Names'].replace(name_to_replace_dict, inplace = True)

Let's look at the number of names left that were not mismatches

In [ ]:
names_set1 = set(df_salary_exploded['Names'])
names_set2 = set(player_statistics_country['PLAYER_NAME'])

# Players present in the first dataset but not in the second dataset
in_df1_not_in_df2 = names_set1 - names_set2

# Players present in the second dataset but not in the first dataset
in_df2_not_in_df1 = names_set2 - names_set1

# Print the discrepancies
print("Players in salary but not in stats:")
print(in_df1_not_in_df2)

print("\nPlayers in stats but not in salary:")
print(in_df2_not_in_df1)

Players in salary but not in stats:
{'Ben Sheppard', 'Melo Trimble', 'Christian Watford', 'Jordan Henriquez', 'Mark Ogden', 'Shawn Dawson', 'Brady Heslip', 'Shizz Alston', 'BJ Young', 'Matthew Hurt', 'Bryce Hamilton', 'Robert Vaden', 'Brock Motum', 'Paul Eboua', 'Rick Jackson', 'Matur Maker', 'Max Heidegger', 'Michael Eric', 'Nikola Jovanovic', 'Brandon Rachal', 'Nate Sestina', 'Christian Vital', 'Kyle Casey', 'Mustapha Farrakhan', 'Fuquan Edwin', 'Rayan Rupert', 'Vashil Fernandez', 'Dmytro Skapintsev', 'Kleon Penn', 'George Conditt', 'Stefhon Hannah', 'Jordan Vandenberg', 'Aamir Simms', 'Shawn Jones', 'Edgar Sosa', 'Tony Gaffney', 'Jordan Railey', 'Eric Griffin', 'Jake Anderson', 'Goran Suton', 'Darryl Morsell', 'Zach Smith', 'Ronald Roberts', 'Bilal Coulibaly', 'Alex Antetokounmpo', "Maurice N'dour", 'Quinton Rose', 'Jacob Toppin', 'CJ Aiken', 'Oscar Bellfield', 'Matt Janning', 'Dan Nwaelele', 'Tomislav Zubcic', 'LJ Figueroa', 'Remi Yusuf', 'Greg Somogyi', 'John Petty', 'Maxwell Lewis', 'Michael Qualls', 'Marshall Henderson', 'Kenny Gabriel', 'Jeremy Senglin', 'Romaro Gill', 'Kenny Wooten', 'Trey Lewis', 'Carleton Scott', 'Devonte Patterson', "Sir'Dominic Pointer", 'Phil Jones', 'Erik Atkins', 'Andrew Andrews', 'Akil Mitchell', 'Devin Sweetney', 'Jeffrey Carroll', 'Stanley Robinson', 'Deshaun Thomas', 'Stephen Dennis', 'Julian Strawther', 'Chad Brown', 'Pete Nance', 'LiAngelo Ball', 'Dedric Lawson', 'Nate Renfro', 'Ismaila Kane', 'Jakeenan Gant', 'Ethan Thompson', 'Kellan Grady', 'Jaleel Cousins', 'Damion Baugh', 'David Lighty', 'Luke Hancock', 'CJ Fair', 'Mouhamed Gueye', 'Chris Walker', 'Anthony Duruji', 'Abdul Gaddy', 'Justin Simon', 'Nicholas King', 'Thomas Walkup', 'Larry Bird', "D'Aundray Brown", 'TJ Williams', 'Marcus Sasser', 'Khalif Wyatt', 'Wesley Witherspoon', 'Mirza Begic', 'Joe Jackson', 'Isaiah Pineiro', 'Eric Boateng', 'Brandon McCoy', 'Magnum Rolle', 'Mitchell Watt', 'Keandre Cook', 'Dariq Whitehead', 'Charlie Westbrook', 'Aaron Craft', 'Anthony Tarke', 'Juwan Staten', 'Victor Wembanyama', 'Jeriah Horne', 'Joel Berry', 'Ibou Badji', 'Jules Bernard', 'Matt Farrell', 'Roy Marble', 'Richard Solomon', 'Bronson Koenig', 'Angel Rodriguez', 'Prince Ibeh', 'Jaron Johnson', 'Aric Holman', 'Romeo Weems', 'John Egbunu', 'Bryson Williams', 'Luke Maye', 'Brandin Podziemski', 'Matthew Mayer', 'Breein Tyree', 'Alex Robinson', 'Kennedy Meeks', 'Darion Atkins', 'Ryan Boatright', 'Marcus Simmons', 'Arsalan Kazemi', 'Michale Kyser', 'Iverson Molinar', 'Trey Freeman', 'Levi Randolph', 'Brian Butch', "Da'Sean Butler", 'Jarrid Famous', 'James Akinjo', 'Justin Cobbs', 'Alec Brown', 'Carlos Morais', 'Jahlil Tripp', 'John Bohannon', 'Lance Goulbourne', 'Mac Koshwal', 'Jermaine Samuels', 'Christ Koumadje', 'Marcus Bingham', 'Andrew Funk', 'Filip Petrusev', 'Justin Tillman', 'Tosan Evbuomwan', 'Marcus Foster', 'Tu Holloway', 'Quincy Ford', 'Leonard Miller', 'Kenny Kadji', 'Nate Pierre-Louis', 'Damen Bell-Holter', 'Scoot Henderson', 'Nick Zeisloft', 'Jamar Smith', 'Courtney Fells', 'Nick Minnerath', 'Jaime Echenique', 'Colby Jones', 'Ryan Richards', 'Marcus Zegarowski', 'Scottie Wilbekin', 'Cameron Jones', 'Nick Wiggins', 'Scottie Lindsey', 'DJ Steward', 'Kenny Hasbrouck', 'Corey Webster', 'Charles Matthews', 'Tres Tinkle', 'JP Tokoto', 'Tidjan Keita', 'Lamar Peters', 'Bo McCalebb', 'Oleksandr Kobets', 'Corey Hawkins', 'Sagaba Konate', 'Drake Jeffries', 'Marcus Lee', 'Keyonte George', 'Olivier Hanlan', 'Johnny Hamilton', 'Robert Johnson', 'Michael Lee', 'Ryan Allen', 'Rasheed Sulaimon', 'Kadeem Jack', 'Kobe Brown', 'EJ Liddell', 'Ding Yanyuhang', 'Elijah Pemberton', 'Ibi Watson', 'Trevon Bluiett', 'Mitch Ballock', 'Chris Udofia', 'Caleb Homesley', 'Gracin Bakumanya', 'Mamadou N’Diaye', 'Sidy Cissoko', 'Stephen Holt', 'Jordan Ford', 'Chris Daniels', 'Brice Sensabaugh', 'William McDowell-White', 'Jordan Hawkins', 'Bryce Brown', 'Dereck Lively', 'Kadeem Batts', 'Travis Trice', 'Reginald Becton', 'Lazeric Jones', 'Trent Plaisted', 'Richard Howell', 'Jalen Hood-Schifino', 'Barry Brown', 'Seth Tarver', 'Tony Carr', 'Makur Maker', 'Kahlil Whitney', 'Jeremiah Tilmon', 'Derek Culver', 'Carlon Brown', 'Bennie Boatwright', 'Toumani Camara', 'Egidijus Mockevicius', 'Kyle Fogg', 'Michael Holyfield', 'EJ Singler', 'CJ Massinburg', 'Devontae Shuler', 'Jordan Mathews', 'Keith Hornsby', 'Tiwian Kendley', 'Kaiser Gates', 'Nick Smith', 'Noah Clowney', 'Stefan Jankovic', 'Julian Phillips', 'Sam Thompson', 'Jarace Walker', 'Yanick Moreira', 'Micah Downs', 'Dakarai Allen', 'BJ Taylor', 'Chris Livingston', 'Roscoe Smith', 'Markel Crawford', 'Myck Kabongo', 'Kaleb Tarczewski', 'Tyus Battle', 'Jaleel Roberts', 'John Shurna', 'Rade Zagorac', 'Will Cummings', 'DJ Hogg', 'Brian Qvale', 'Romero Osby', 'Denzel Mahoney', 'Wesley Saunders', 'Rodney Williams', 'George Paula', 'Desi Rodriguez', 'Jordan Bachynski', 'Grant Golden', 'Orlando Sanchez', 'Nuni Omot', 'David Kramer', 'Doral Moore', 'DJ Stewart', 'Terry Larrier', 'Steven Gray', 'Tre Kelley', 'Talib Zanna', 'Vasilije Micic', 'Amen Thompson', 'Henri Drell', 'LJ Peak', 'Malik Ellison', 'Scott Wood', 'Kobe Bufkin', 'Chet Holmgren', 'Marcus Denmon', 'AJ Reeves', 'Rayshaun Hammonds', 'Gabe Brown', 'Isaac Hamilton', 'Sampson Carter', 'James Banks', 'Olivier-Maxence Prosper', 'Beau Beech', 'Richard McConnell', 'Damien Jefferson', 'Dallas Lauderdale', 'Sacha Killeya-Jones', 'Jaylen Barford', 'Terran Petteway', 'Jonathan Holmes', 'Cason Wallace', 'Dee Bost', 'Shannon Scott', 'Michael Dunigan', 'Isaiah Cousins', 'Yoeli Childs', 'Trayce Jackson-Davis', 'Peter Jok', 'Landry Nnoko', 'Justin Powell', 'Reeves Nelson', 'DJ Carton', 'Brandon Heath', 'Kaleb Wesson', 'Casey Prather', 'Brandon Miller', 'Justin Smith', 'Marqus Blakely', 'Luca Vildoza', 'Josh Bostic', 'Elijah Stewart', 'Drew Crawford', 'Robert Upshaw', 'Luke Nevill', 'Devin Searcy', 'Terry Henderson', 'Sergey Gladyr', 'Anthony Black', 'Jaylen Johnson', 'Ronnie Aguilar', 'Isaac Haas', 'Trent Lockett', 'Jordan Walsh', 'Olek Czyz', 'Jake Toolson', 'Terrico White', 'Nick Ongenda', 'Justin Brownlee', 'Ronshad Shabazz', 'Jordan Barnett', 'MaCio Teague', 'Jason Washburn', 'VJ Beachem', 'Simisola Shittu', 'Magic Johnson', 'Canyon Barry', 'Kenny Williams', 'Patric Young', 'Jordan Murphy', 'Dikembe Dixson', 'Troy Baxter', 'James Mays', 'Jon Horford', 'DeShawn Sims', 'Denzel Livingston', 'Dez Wells', 'Kamari Murphy', 'Giorgi Bezhanishvili', 'Jaime Jaquez', 'Gradey Dick', 'Michael Cobbins', 'Sedrick Barefield', 'Jordan Burns', 'Josh Owens', 'Rashawn Thomas', 'Devin Williams', 'Corey Walden', 'Jonathan Stark', 'Jett Howard', 'Hunter Tyson', 'Kammron Taylor', "D'or Fischer", 'EJ Montgomery', 'VJ King', 'Phil Carr', 'James Blackmon', 'Zak Irvin', 'Galen Robinson', 'Garrison Brooks', 'Zach Auguste', 'Robert Dozier', 'Kris Murray', 'Yudai Baba', 'Perry Ellis', 'Michael Devoe', 'Demonte Harper', 'CJ Leslie', 'Elgin Cook', 'Cam Whitmore', 'Taylor Hendricks', 'Nnanna Egwu', 'Andre Jackson', 'Youssou Ndoye', 'Hank Thorns', 'Yuki Togashi', 'Brandon Ashley', 'Davion Mintz', 'Trevion Williams', 'Yannis Morin', 'Melvin Ejim', 'Jalen Pickett', 'Rob Gray', 'BJ Mullens', 'Anthony Lawrence', 'Reginald Kissoonlal', 'Taylor Funk', 'Sasha Vezenkov', 'Livio Jean-Charles', 'Ron Howard', 'Diamon Simpson'}

Players in stats but not in salary:

In [ ]:
#number of players that supposedly did not play in the nba (ever or yet)
len(in_df1_not_in_df2)

428

During the merging of all the datasets in the next section, these 428 player names will be automatically dropped by the join statement.

In [ ]:
#check if replacement worked 
names_not_relevant = set(name_mismatch_filled['names'][name_mismatch_filled['mismatch'].isnull()])
set(df_salary_exploded['Names'])-names_in_stats-names_not_relevant

set()

The empty set indicates that all the mismatched names were properly updated. Finally, we will eliminate or drop those columns that will not be utilized in our future analysis

In [ ]:
#list of columns
df_salary_exploded.columns

Index(['Rank', 'Player', 'Signed Age', 'Yrs', 'Value', 'AAV', 'Sign Bonus',
       'Names', 'Positions', 'Start_Year', 'End_Year', 'FreeAgent_Year',
       'AAVClean', 'ValueClean', 'Sign BonusClean', 'AAV+Bonus', 'Value+Bonus',
       'Year_List'],
      dtype='object')

In [ ]:

#dropping unnecessary columns
df_salary_exploded.drop(
    columns = [
        "Signed Age",
        "Value",
        "AAV",
        "Sign Bonus",
        "Player",
        "Start_Year",
        "End_Year",
        "Rank",
        "Yrs",
        "FreeAgent_Year",
        "Sign BonusClean",
        "AAVClean",
        "ValueClean",
        "Value+Bonus"

    ],
    inplace = True,
)

### 3. Merge combined Primary and Secondary 'Statistics and Country Dataset' with the Tertiary 'Salary Dataset'

In [ ]:
#look at the years of season_id range and Year_List range 
print('all years in player_statistics_country dataset: ', pd.unique(player_statistics_country["season_id"]))
print('all years in tertiary salary dataset: ', pd.unique(df_salary_exploded["Year_List"]))

# Merge
df_statistics_salary = player_statistics_country.merge(
    df_salary_exploded,
    left_on=["PLAYER_NAME", "season_id"],
    right_on=["Names", "Year_List"],
)

all years in player_statistics_country dataset:  [1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009
 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022]
all years in tertiary salary dataset:  [2022 2023 2024 2025 2026 2018 2019 2020 2021 2027 2028 2017 2016 2013
 2014 2015 2003 2004 2005 2006 2007 2008 2012 1999 2000 2001 2002 1996
 1997 1998 1994 1995 2009 2010 2011 1993 1984 1985 1986 1987 1988 1989
 1990 1991 1992 1979 1980 1981 1982 1983]

We should also check if the instances of names and years present in the salary dataset are not in the statistics dataset. While all the names are accounted for previously for the salary and statistics due to mismatches or players never playing NBA games, we should also further inspect year instances.

In [ ]:
#list of names and years in the salary dataset
full_names = df_salary_exploded["Names"]
full_years = df_salary_exploded["Year_List"]

#initialize list for name, year missing in statistics dataset
lst_name_year_missing = []

#append list for missing names and years
for name, year in zip(full_names, full_years):
    if name in list(df_statistics_salary.loc[:, 'Names']) and len(df_statistics_salary['Year_List'][(df_statistics_salary['Year_List'] == year) & (df_statistics_salary['Names'] == name)]) > 0:
        continue
    else:
        if year < 2023 and year > 1995 and name not in names_not_relevant:
            lst_name_year_missing.append([name, year])

#print list
print(lst_name_year_missing)

[['Ben Simmons', 2021], ['John Wall', 2019], ['John Wall', 2021], ['Jamal Murray', 2021], ['Derrick Rose', 2012], ['Lonzo Ball', 2022], ['Eric Bledsoe', 2022], ['Brandon Knight', 2017], ['Baron Davis', 2012], ['Charlie Bell', 2011], ['Marko Jaric', 2009], ['Marko Jaric', 2010], ['Jamaal Tinsley', 2008], ['Jamaal Tinsley', 2010], ['Antonio Daniels', 2009], ['Steve Nash', 2014], ['Ben Simmons', 2016], ['Speedy Claxton', 2007], ['Speedy Claxton', 2009], ['Shaun Livingston', 2019], ['DJ Augustin', 2022], ['Rodney Stuckey', 2017], ['Dante Exum', 2015], ['Damon Jones', 2009], ['Damon Jones', 2010], ['Damon Jones', 2011], ['Chris Duhon', 2013], ['CJ Watson', 2017], ['Shaun Livingston', 2007], ['Jay Williams', 2003], ['Jay Williams', 2004], ['Kendrick Nunn', 2021], ['Tony Parker', 2019], ['Trey Burke', 2022], ['TJ Ford', 2004], ['Jason Kidd', 2013], ['Jason Kidd', 2014], ['Wade Baldwin', 2019], ['Dante Exum', 2021], ['Dante Exum', 2022], ['Kendall Marshall', 2016], ['Kendall Marshall', 2017], ['Kendall Marshall', 2018], ['Tyrell Terry', 2022], ['Javaris Crittenton', 2009], ['Javaris Crittenton', 2010], ['Javaris Crittenton', 2011], ['Dejounte Murray', 2018], ['Quincy Douby', 2009], ['Quincy Douby', 2010], ['Michael Carter-Williams', 2021], ['Isaiah Briscoe', 2019], ['Isaiah Briscoe', 2020], ['Isaiah Briscoe', 2021], ['Demetrius Jackson', 2019], ['Ronnie Price', 2017], ['Nigel Williams-Goss', 2020], ['Nigel Williams-Goss', 2021], ['Mardy Collins', 2010], ['Isaiah Whitehead', 2018], ['Isaiah Whitehead', 2019], ['Jason Preston', 2021], ['Elie Okobo', 2020], ['Mo Williams', 2016], ['Jalen Lecque', 2021], ['Eric Maynor', 2014], ['Roko Ukic', 2010], ['Jerian Grant', 2020], ['Jerian Grant', 2021], ['Tyler Ulis', 2019], ['Frank Jackson', 2017], ['Darius Morris', 2018], ['Darius Morris', 2019], ['Kevin Pangos', 2022], ['Isaiah Taylor', 2019], ['Isaiah Taylor', 2020], ['Kyle Collinsworth', 2018], ['Kyle Collinsworth', 2019], ['Tyler Ennis', 2018], ['Nate Wolters', 2016], ['Nate Wolters', 2018], ['Chasson Randle', 2017], ['Marcelo Huertas', 2017], ['Darius Morris', 2015], ['Marquis Teague', 2014], ['Isaiah Taylor', 2018], ['Shane Larkin', 2016], ['Isaiah Taylor', 2018], ['Kyle Weaver', 2011], ['Pierre Jackson', 2015], ['Pierre Jackson', 2017], ['Diante Garrett', 2014], ['Diante Garrett', 2015], ['JJ Barea', 2020], ['Semaj Christon', 2017], ['Semaj Christon', 2018], ['Kay Felder', 2018], ['Jonathan Gibson', 2018], ['Jarrett Jack', 2018], ['Brandon Jennings', 2018], ['Dwight Buycks', 2018], ['Erick Green', 2016], ['Russ Smith', 2016], ['Beno Udrih', 2017], ['Emmanuel Mudiay', 2022], ['John Lucas', 2007], ['John Lucas', 2008], ['Nate Wolters', 2015], ['Gal Mekel', 2015], ['Pablo Prigioni', 2016], ['Pablo Prigioni', 2017], ['Scott Machado', 2013], ['Scott Machado', 2014], ['Nemanja Nedovic', 2014], ['Quinn Cook', 2022], ['Chris Clemons', 2020], ['Bryce Dejean-Jones', 2016], ['Bryce Dejean-Jones', 2017], ['Chasson Randle', 2022], ['Chris Chiozza', 2022], ['Quinn Cook', 2021], ['Bryce Cotton', 2016], ['Diante Garrett', 2014], ['Diante Garrett', 2015], ['Jerel McNeal', 2012], ['Jerel McNeal', 2013], ['David Stockton', 2022], ['Chasson Randle', 2021], ['Casper Ware', 2014], ['Casper Ware', 2015], ['Casper Ware', 2016], ['Donald Sloan', 2018], ['Tyler Ennis', 2019], ['Frank Mason', 2021], ['Darius Morris', 2015], ['Donald Sloan', 2017], ['Walt Lemon', 2019], ['Jaylen Adams', 2019], ['Jorge Gutierrez', 2019], ['Jalen Lecque', 2021], ['David Stockton', 2021], ['Tim Quarterman', 2018], ['Keifer Sykes', 2022], ['Grant Riller', 2022], ['Jalen Harris', 2022], ['Zavier Simpson', 2022], ['David Johnson', 2022], ['Sharife Cooper', 2022], ['Derrick Walton', 2020], ['Elie Okobo', 2020], ['Xavier Munford', 2019], ['Tyler Ulis', 2019], ['David Stockton', 2019], ['Demetrius Jackson', 2019], ['Kobi Simmons', 2019], ['Walt Lemon', 2019], ['David Stockton', 2018], ['Briante Weber', 2018], ['Julyan Stone', 2018], ['Kendall Marshall', 2017], ['Kay Felder', 2018], ['Isaiah Taylor', 2018], ['Ashton Hagans', 2021], ['Maalik Wayns', 2017], ['Chasson Randle', 2017], ['Marcus Paige', 2016], ['Ryan Arcidiacono', 2016], ['Kyle Collinsworth', 2016], ['Cat Barber', 2016], ['Cat Barber', 2017], ['Justin Wright-Foreman', 2020], ['Jaylen Adams', 2019], ['Troy Caupain', 2019], ['Kyle Collinsworth', 2019], ['Will Bynum', 2016], ['John Lucas', 2015], ['Will Cherry', 2015], ['Chris Crawford', 2014], ['Chris Crawford', 2015], ['Anthony Carter', 2012], ['Kyle Collinsworth', 2018], ['Derrick Walton', 2018], ['Will Cherry', 2015], ['Kalin Lucas', 2017], ['Josh Selby', 2013], ['Chris Quinn', 2013], ['Marko Jaric', 2013], ['Patrick Beverley', 2010], ['Patrick Beverley', 2011], ['Sam Cassell', 2008], ['Eddie Gill', 2012], ['Delonte West', 2012], ['Marko Jaric', 2012], ['Henry Walker', 2015], ['Sean Singletary', 2009], ['Gabe Pruitt', 2009], ['Stephen Graham', 2013], ['Lester Hudson', 2015], ['Zabian Dowdell', 2011], ['Lorenzo Brown', 2016], ['Julyan Stone', 2016], ['Ray McCallum', 2016], ['Phil Pressey', 2016], ['Jorge Gutierrez', 2016], ['Stephen Graham', 2011], ['Von Wafer', 2012], ['Von Wafer', 2013], ['Julyan Stone', 2015], ['Jerel McNeal', 2015], ['Lester Hudson', 2013], ['Orien Greene', 2012], ['Jeff Dowtin', 2020], ['Ahmad Caver', 2019], ['Devin Cannady', 2019], ['Jaylen Adams', 2019], ['Ahmad Caver', 2020], ['Zavier Simpson', 2020], ['Kyle Weaver', 2012], ['Derrick Brown', 2012], ['Jonny Flynn', 2012], ['Sundiata Gaines', 2012], ['Casper Ware', 2016], ['Xavier Munford', 2016], ['David Stockton', 2015], ['Othyus Jeffers', 2012], ['Armon Johnson', 2012], ['Ben Uzoh', 2012], ['Ben Uzoh', 2012], ['Gabe Vincent', 2018], ['Will Cherry', 2018], ['Jordan McLaughlin', 2018], ['Gabe York', 2018], ['Kendrick Nunn', 2018], ['Ben Hansbrough', 2014], ['Peyton Siva', 2014], ['Marcus Williams', 2017], ['Troy Caupain', 2017], ['Isaiah Briscoe', 2017], ['Josh Akognon', 2013], ['Scott Machado', 2013], ['Scott Machado', 2013], ['Rafer Alston', 2010], ['Jay Williams', 2006], ['Walker Russell', 2012], ['Shaquille Harrison', 2016], ['Josh Magette', 2016], ['Chris Crawford', 2016], ['Deonte Burton', 2015], ['Quinn Cook', 2015], ['Keifer Sykes', 2015], ['Pierre Jackson', 2014], ['Deonte Burton', 2014], ['Chris Crawford', 2014], ['Keith Appling', 2014], ['Kalin Lucas', 2013], ['Larry Drew', 2013], ['Jerel McNeal', 2012], ['Mustafa Shakur', 2009], ['Carlos Arroyo', 2011], ['Jannero Pargo', 2010], ['Larry Hughes', 2010], ['Ty Lawson', 2017], ['Klay Thompson', 2019], ['Klay Thompson', 2020], ['Allan Houston', 2005], ['Allan Houston', 2006], ['Dion Waiters', 2020], ['Monta Ellis', 2017], ['Monta Ellis', 2018], ['Andre Roberson', 2018], ['Greg Buckner', 2009], ['Greg Buckner', 2010], ['Kevin Martin', 2016], ['Jason Richardson', 2013], ['Gerald Henderson', 2017], ['David Nwaba', 2022], ['Quincy Pondexter', 2015], ['Quincy Pondexter', 2016], ['Zhaire Smith', 2020], ['Brandon Roy', 2013], ['Richard Hamilton', 2013], ['Denzel Valentine', 2018], ['Raja Bell', 2012], ['Cuttino Mobley', 2009], ['Jacob Evans', 2020], ['Dzanan Musa', 2020], ['Leandro Barbosa', 2017], ['Armoni Brooks', 2022], ['Malachi Richardson', 2019], ['Mike Miller', 2017], ['Terrence Williams', 2013], ['Carlos Delfino', 2013], ['Carlos Delfino', 2014], ['Carlos Delfino', 2015], ['Edmond Sumner', 2021], ['Sean Kilpatrick', 2018], ['Sean Kilpatrick', 2019], ['Carlos Delfino', 2013], ['Seth Curry', 2017], ['Sonny Weems', 2016], ['Davon Reed', 2019], ['Davon Reed', 2020], ['Marko Guduric', 2020], ['Manu Ginobili', 2018], ['Sergio Rodriguez', 2010], ['Robert Woodard', 2022], ["Jahmi'us Ramsey", 2022], ['Jordan Adams', 2016], ['Justin James', 2021], ['Sasha Pavlovic', 2013], ['Sasha Pavlovic', 2014], ['Elliot Williams', 2010], ['Elliot Williams', 2012], ['Justin Anderson', 2020], ['Brent Barry', 2009], ['Mario Hezonja', 2020], ['Dwayne Bacon', 2021], ['Zoran Dragic', 2015], ['Shabazz Muhammad', 2018], ['Antonius Cleveland', 2018], ['Ricky Ledo', 2015], ['Ricky Ledo', 2016], ['Carrick Felix', 2014], ['Carrick Felix', 2015], ['Carrick Felix', 2016], ['John Jenkins', 2017], ['CJ Williams', 2019], ['Malcolm Lee', 2016], ['Malcolm Lee', 2017], ['Jabari Bird', 2018], ['Jabari Bird', 2019], ['Antonio Blakeney', 2019], ['Langston Galloway', 2022], ['Kent Bazemore', 2022], ['Eddie House', 2011], ["E'Twaun Moore", 2021], ['Joe Johnson', 2019], ['Gerald Green', 2019], ['Gerald Green', 2020], ['Courtney Lee', 2020], ['Michael Gbinije', 2017], ['Michael Gbinije', 2018], ['Luis Montero', 2016], ['DeAndre Liggins', 2018], ['Nick Johnson', 2015], ['Nick Johnson', 2016], ['Justin Anderson', 2022], ['Denzel Valentine', 2022], ['Timothe Luwawu-Cabarrot', 2022], ['Orlando Johnson', 2014], ['Tony Wroten', 2016], ['Tony Wroten', 2017], ['Brandon Paul', 2018], ['James Anderson', 2016], ['Malcolm Lee', 2013], ['Patrick McCaw', 2022], ['Josh Jackson', 2022], ['Travis Leslie', 2012], ['Travis Leslie', 2013], ['Anthony Morrow', 2017], ['Brandon Rush', 2017], ['Hollis Thompson', 2012], ['Morris Almond', 2009], ['Morris Almond', 2010], ['Brent Barry', 2009], ['Nik Stauskas', 2020], ['Archie Goodwin', 2017], ['Dwayne Bacon', 2022], ['DaQuan Jeffries', 2022], ['Jerome Robinson', 2022], ['Daniel Ewing', 2007], ['Chris Babb', 2014], ['Chris Babb', 2015], ['Adam Mokoka', 2022], ['Armoni Brooks', 2022], ['Robert Woodard', 2022], ["Jahmi'us Ramsey", 2022], ['Nate Hinton', 2022], ['Dwayne Bacon', 2021], ['Jared Cunningham', 2021], ['Kevin Murphy', 2014], ['Kevin Murphy', 2015], ['James White', 2013], ['DeAndre Liggins', 2018], ['Shabazz Muhammad', 2018], ['James Young', 2020], ['Jared Cunningham', 2019], ['Hollis Thompson', 2019], ['Axel Toupane', 2021], ['CJ Wilcox', 2019], ['Naz Mitrou-Long', 2020], ['Elijah Millsap', 2019], ['Markel Brown', 2019], ['Xavier Silas', 2018], ['Brian Bowen', 2021], ['Justin James', 2021], ['Marial Shayok', 2022], ['Dakota Mathias', 2022], ['Nate Darling', 2022], ['Tyler Hall', 2022], ['Rob Edwards', 2022], ['Archie Goodwin', 2017], ['James Young', 2018], ['Rashad Vaughn', 2018], ['Andrew Harrison', 2019], ['Antonius Cleveland', 2020], ['Zhaire Smith', 2020], ['CJ Williams', 2019], ['Davon Reed', 2019], ['Dairis Bertans', 2019], ['John Jenkins', 2017], ['Archie Goodwin', 2017], ['KJ McDaniels', 2018], ['Elijah Millsap', 2017], ['KJ McDaniels', 2017], ['Marcus Georges-Hunt', 2018], ['Jason Richardson', 2015], ['Ben Gordon', 2015], ['Axel Toupane', 2017], ['Elijah Bryant', 2021], ['Nate Darling', 2021], ['DJ Stephens', 2016], ['DJ Stephens', 2017], ['Sheldon Mac', 2017], ['Brandon Paul', 2016], ['Damion Lee', 2016], ['Zach Norvell', 2020], ['Ky Bowman', 2020], ['Josh Reaves', 2020], ['DeVaughn Akoon-Purcell', 2019], ['Jordan Sibert', 2019], ['Daniel Hamilton', 2019], ['Michael Frazier', 2015], ['Michael Frazier', 2016], ['Andy Rautins', 2011], ['Damien Wilkins', 2015], ['Darius Johnson-Odom', 2018], ['Nick Johnson', 2018], ['Carrick Felix', 2017], ['Michael Gbinije', 2017], ['Chris Smith', 2014], ['Damien Wilkins', 2013], ['Kim English', 2013], ['Kevin Murphy', 2013], ['Dionte Christmas', 2012], ['Chris Smith', 2012], ['Patrick Christopher', 2015], ['Flip Murray', 2012], ['Tony Wroten', 2016], ['Terrence Williams', 2013], ['Chris Douglas-Roberts', 2015], ['Mike Taylor', 2009], ['Xavier Henry', 2016], ['Xavier Henry', 2015], ['Elliot Williams', 2016], ['Orlando Johnson', 2016], ['Jordan Crawford', 2015], ['Chris Babb', 2014], ['Chris Babb', 2015], ['Ricky Ledo', 2015], ['Damion James', 2014], ['PJ Hairston', 2016], ['Markel Brown', 2016], ['Terrel Harris', 2013], ['Jamaal Franklin', 2015], ['Tyler Bey', 2021], ['Dru Smith', 2021], ['Doron Lamb', 2014], ['James White', 2009], ['Armoni Brooks', 2019], ['Shaq Buchanan', 2019], ['Hassani Gravett', 2019], ['Julian Washburn', 2019], ['Andre Dawkins', 2019], ['Tyler Hall', 2020], ['Shaq Buchanan', 2020], ['Johnny Davis', 2019], ['Trevelin Queen', 2020], ['Kevon Harris', 2020], ['Myles Powell', 2020], ['Xavier Sneed', 2020], ['Lindell Wigginton', 2019], ['Dakota Mathias', 2019], ['Jabari Brown', 2015], ['Blake Ahearn', 2012], ['Jermaine Taylor', 2013], ['DJ Kennedy', 2016], ['Kevin Murphy', 2016], ['Dionte Christmas', 2016], ['Nick Johnson', 2016], ['Jabari Brown', 2016], ['Luis Montero', 2016], ['Anthony Roberson', 2009], ['Coby Karl', 2012], ['Dionte Christmas', 2015], ['Patrick Christopher', 2015], ['DJ Stephens', 2015], ['Paul Watson', 2018], ['Justin Holiday', 2013], ['Xavier Silas', 2014], ['Kim English', 2014], ['Dionte Christmas', 2014], ['DJ Stephens', 2014], ['Andy Rautins', 2017], ['DJ Kennedy', 2013], ['Xavier Silas', 2013], ['Justin Holiday', 2013], ['DJ Kennedy', 2012], ['Jermaine Taylor', 2012], ['Andy Rautins', 2012], ['Carldell Johnson', 2012], ['CJ Williams', 2016], ['Alex Caruso', 2016], ['Jordan Sibert', 2015], ['Julian Washburn', 2015], ['Rodney McGruder', 2014], ['Patrick Christopher', 2013], ['Trey McKinney-Jones', 2013], ['Rodney McGruder', 2013], ['Darington Hobson', 2010], ['Tracy McGrady', 2012], ['Kawhi Leonard', 2021], ['Kevin Durant', 2019], ['Kawhi Leonard', 2021], ['Grant Hill', 2003], ['Luol Deng', 2019], ['Kevin Durant', 2019], ['Josh Smith', 2016], ['Jamal Mashburn', 2004], ['Jamal Mashburn', 2005], ['Jamal Mashburn', 2006], ['TJ Warren', 2021], ['Bobby Simmons', 2006], ['Wilson Chandler', 2015], ['Gerald Wallace', 2015], ['Travis Outlaw', 2014], ['Wilson Chandler', 2015], ['Matt Harpring', 2009], ['Martell Webster', 2015], ['Martell Webster', 2016], ['DeMarre Carroll', 2020], ['DeMarre Carroll', 2021], ['Jonathon Simmons', 2019], ['Kyle Singler', 2018], ['Linas Kleiza', 2013], ['Adam Morrison', 2007], ['Sekou Doumbouya', 2022], ['Keith Bogans', 2014], ['Keith Bogans', 2015], ['Michael Porter', 2018], ['Mike Dunleavy', 2017], ['Darius Miller', 2019], ['Matt Barnes', 2017], ['Travis Outlaw', 2014], ['Paul Pierce', 2017], ['Dylan Windler', 2019], ['Scottie Pippen', 2004], ['Jud Buechler', 2002], ['Kelenna Azubuike', 2010], ['Maurice Harkless', 2022], ['Bruce Bowen', 2009], ['Didi Louzada', 2022], ['Richard Jefferson', 2018], ['Jonah Bolden', 2020], ['Jonah Bolden', 2021], ['Shawne Williams', 2009], ['DeShawn Stevenson', 2013], ['DeShawn Stevenson', 2014], ['Perry Jones', 2015], ['Zylan Cheatham', 2020], ['Zylan Cheatham', 2022], ['Alando Tucker', 2010], ['Alando Tucker', 2011], ['Troy Williams', 2019], ['Georgios Kalaitzakis', 2022], ['Admiral Schofield', 2020], ['Danny Granger', 2015], ['Stanton Kidd', 2020], ['Stanton Kidd', 2021], ['William Howard', 2020], ['William Howard', 2021], ['Deividas Sirvydis', 2022], ['Abdel Nader', 2022], ['Paul Zipser', 2018], ['Paul Zipser', 2019], ['Metta Peace', 2014], ['Caron Butler', 2016], ['Gary Forbes', 2012], ['James Nunnally', 2019], ['Scotty Hopson', 2014], ['Gani Lawal', 2013], ['Gani Lawal', 2014], ['Gani Lawal', 2015], ['Damien Inglis', 2014], ['Damien Inglis', 2016], ['Shawne Williams', 2015], ['Daniel Ochefu', 2017], ['Daniel Ochefu', 2018], ['Nicolas Brussino', 2018], ['Ronnie Brewer', 2014], ['Melvin Frazier', 2020], ['Bruno Caboclo', 2022], ['Jamil Wilson', 2015], ['Jamil Wilson', 2016], ['JaKarr Sampson', 2016], ['Martell Webster', 2017], ['Jeremy Evans', 2016], ['Michael Kidd-Gilchrist', 2020], ['Jake Layman', 2022], ['Chris Johnson', 2016], ['Wes Iwundu', 2022], ['Wes Iwundu', 2022], ['Ryan Reid', 2012], ['Ryan Reid', 2013], ['Shawne Williams', 2017], ['Josh Childress', 2017], ['Joey Graham', 2011], ['Keith Booth', 1999], ['Robbie Hummel', 2016], ['Robbie Hummel', 2017], ["Toure' Murry", 2015], ['Scotty Hopson', 2022], ['Sekou Doumbouya', 2022], ['Juwan Morgan', 2022], ['Kelan Martin', 2022], ['Rayjon Tucker', 2022], ['Darius Miller', 2015], ['Deividas Sirvydis', 2022], ['Zylan Cheatham', 2022], ['Elijah Hughes', 2022], ['CJ Elleby', 2022], ['Adonis Thomas', 2015], ['Adonis Thomas', 2016], ['Kostas Papanikolaou', 2016], ['Chris Hunter', 2010], ['Trey Johnson', 2012], ['Treveon Graham', 2020], ['Malcolm Miller', 2020], ['Sean McDermott', 2022], ['Chaundee Brown', 2022], ['Jamorko Pickett', 2022], ['MJ Walker', 2022], ['Aleem Ford', 2022], ['Jalen Jones', 2019], ['Jarrod Uthoff', 2020], ['Devin Robinson', 2020], ['Melvin Frazier', 2020], ['Ryan Broekhoff', 2020], ['BJ Johnson', 2020], ['Troy Williams', 2019], ['Devin Robinson', 2019], ['Joe Alexander', 2010], ['Chris Johnson', 2017], ['Josh Huestis', 2018], ['Anthony Brown', 2018], ['Dorell Wright', 2016], ['Rasual Butler', 2016], ['Reggie Williams', 2015], ['Perry Jones', 2017], ['Damjan Rudez', 2017], ['Scotty Hopson', 2018], ['Josh Hall', 2021], ['Vincent Edwards', 2021], ['Sean McDermott', 2021], ['Chris Wright', 2017], ['Patricio Garino', 2017], ['James Webb', 2016], ['Jarrod Uthoff', 2017], ['Patricio Garino', 2017], ['Jaron Blossomgame', 2019], ['Vincent Edwards', 2019], ['Vincent Edwards', 2020], ['Zylan Cheatham', 2020], ['Myke Henry', 2019], ['Deng Adel', 2019], ['Omari Johnson', 2018], ['Thanasis Antetokounmpo', 2016], ['Branden Dawson', 2016], ['Corey Maggette', 2013], ['Dahntay Jones', 2013], ['Jarrod Uthoff', 2017], ['Omari Johnson', 2018], ['Jamel Artis', 2018], ['Jamel Artis', 2018], ['Jason Kapono', 2014], ['Chase Budinger', 2016], ['DeQuan Jones', 2017], ['Daniel Ochefu', 2017], ['Jarrod Uthoff', 2017], ['Elias Harris', 2014], ['Adonis Thomas', 2014], ['Mickael Gelabale', 2013], ['Pape Sy', 2011], ['Derrick Caracter', 2011], ['Kris Joseph', 2013], ['Gani Lawal', 2011], ['Earl Clark', 2015], ['JaKarr Sampson', 2016], ['Quincy Miller', 2015], ['Dominic McGuire', 2013], ['Jeff Adrien', 2015], ['Chris Copeland', 2016], ['Donte Greene', 2012], ['Donte Greene', 2013], ['Pops Mensah-Bonsu', 2014], ['Chris Wright', 2016], ["Toure' Murry", 2016], ['Damien Inglis', 2016], ['Cleanthony Early', 2016], ['JaKarr Sampson', 2016], ['Joe Alexander', 2014], ['Chris Singleton', 2014], ['Pops Mensah-Bonsu', 2013], ['Sam Young', 2013], ["Toure' Murry", 2015], ['Chris Wright', 2014], ['Joe Alexander', 2013], ['Devin Ebanks', 2013], ['Adam Morrison', 2012], ['Tre Scott', 2020], ['Ade Murkey', 2020], ['Alando Tucker', 2012], ['Gary Forbes', 2013], ['Derrick Byars', 2013], ['John Holland', 2015], ['John Holland', 2016], ['Travis Wear', 2016], ['John Holland', 2016], ['Branden Dawson', 2016], ["JJ O'Brien", 2016], ['Derrick Byars', 2012], ['DeQuan Jones', 2015], ['James Southerland', 2014], ['Adonis Thomas', 2014], ['Shane Edwards', 2014], ['Kris Joseph', 2013], ['Kris Joseph', 2013], ['DeQuan Jones', 2013], ['Trey Gilder', 2012], ['Jalen Jones', 2016], ['Malcolm Miller', 2015], ['Treveon Graham', 2015], ['Greg Whittington', 2015], ['Omari Johnson', 2015], ['Trey Johnson', 2014], ['John Holland', 2014], ['Jamil Wilson', 2014], ['Jarell Eddie', 2014], ['Malik Allen', 2000], ['Dorell Wright', 2015], ['Chris Bosh', 2016], ['Chris Bosh', 2017], ['Chris Bosh', 2018], ['Raef LaFrentz', 2008], ['Jonathan Isaac', 2021], ['Danilo Gallinari', 2022], ['Antonio McDyess', 2002], ['Zion Williamson', 2021], ['Danilo Gallinari', 2013], ['Jon Leuer', 2019], ['Tyrus Thomas', 2013], ['Andres Nocioni', 2012], ['Jason Caffey', 2003], ['Jason Caffey', 2004], ['Al Harrington', 2014], ['Antoine Walker', 2008], ['Mirza Teletovic', 2018], ['Jason Thompson', 2016], ['Anderson Varejao', 2017], ['Channing Frye', 2012], ['Al-Farouq Aminu', 2021], ['Dario Saric', 2021], ['Carl Landry', 2016], ['Andrew Nicholson', 2017], ['Andrew Nicholson', 2018], ['Andrew Nicholson', 2019], ['James Posey', 2011], ['Zach Randolph', 2018], ['Darrell Arthur', 2018], ['Spencer Hawes', 2017], ['Jonathan Isaac', 2020], ['Rasheed Wallace', 2010], ['Rasheed Wallace', 2011], ['Kristaps Porzingis', 2018], ['Hakim Warrick', 2013], ['Alan Williams', 2019], ['Kevin Garnett', 2016], ['Steven Hunter', 2008], ['Antonio McDyess', 2011], ['Danilo Gallinari', 2022], ['Luka Samanic', 2021], ['Guerschon Yabusele', 2019], ['Furkan Aldemir', 2015], ['Furkan Aldemir', 2016], ['Furkan Aldemir', 2017], ['Brandan Wright', 2009], ['Tim Duncan', 2016], ['Mfiondu Kabengele', 2021], ['Tyler Lydon', 2019], ['Tyler Lydon', 2020], ['Omari Spellman', 2020], ['Jeff Green'

In [ ]:


#save list of names not in stats dataframe
save_not_relevant_names = pd.DataFrame(lst_name_year_missing, columns = ['Name', 'Year']).sort_values(by='Name').to_csv('Missing_Not_Relevant_Names_Stats.csv', index = False)

There are clearly still a lot of unique instances (name, year) in the combined df_statistics_salary that are not in the salary dataset. This may seem odd, since we replaced all the mismatch values but it turns out that these single name, year are the result of the players having a salary contract for that year but not playing in the NBA or having contracts that are not NBA related.

In [ ]:
df_final_statistics_salary = df_statistics_salary.reset_index()
df_final_statistics_salary.drop(columns = ["index"], inplace = True)
df_final_statistics_salary.to_csv("Final_Stats_Salary.csv", index = False)

We have merged the datasets and saved them to csv - lets do a final check of the dataset to make sure it has mostly non-negative values in the columns and it makes sense.

In [ ]:
#check to see if values make sense, their type, and that they are generally  negative 
def makes_sense(df):
    '''The purpose of this function is to check if any values in the 
    final merged dataset are negative'''
    for column in df.columns:
        if df[column].dtypes == int or df[column].dtypes == float:
            print(
                'Negative Values Count for '+ column + ': ', 
                df[column][df[column] < 0].count(), 
            )
            print(
                'NaN values for ' + column + ': ', 
                df[column][df[column].isnull()].count(),
                end = '\n\n'
            )
        else:
            print(
                column + ' is not numerical and is type: ', 
                df[column].dtypes
            )
            print(
                'NaN values for ' + column + ': ', 
                df[column][df[column].isnull()].count(),
                end = '\n\n'
            )

#use greater than zero function to check df_final_statistics_salary
makes_sense(df_final_statistics_salary)

Negative Values Count for PLAYER_ID:  0
NaN values for PLAYER_ID:  0

PLAYER_NAME is not numerical and is type:  object
NaN values for PLAYER_NAME:  0

NICKNAME is not numerical and is type:  object
NaN values for NICKNAME:  0

Negative Values Count for TEAM_ID:  0
NaN values for TEAM_ID:  0

TEAM_ABBREVIATION is not numerical and is type:  object
NaN values for TEAM_ABBREVIATION:  0

Negative Values Count for AGE:  0
NaN values for AGE:  0

Negative Values Count for GP:  0
NaN values for GP:  0

Negative Values Count for W:  0
NaN values for W:  0

Negative Values Count for L:  0
NaN values for L:  0

Negative Values Count for W_PCT:  0
NaN values for W_PCT:  0

Negative Values Count for MIN:  0
NaN values for MIN:  0

Negative Values Count for FGM:  0
NaN values for FGM:  0

Negative Values Count for FGA:  0
NaN values for FGA:  0

Negative Values Count for FG_PCT:  0
NaN values for FG_PCT:  0

Negative Values Count for FG3M:  0
NaN values for FG3M:  0

Negative Values Count for FG3A:  0
NaN values for FG3A:  0

Negative Values Count for FG3_PCT:  0
NaN values for FG3_PCT:  0

Negative Values Count for FTM:  0
NaN values for FTM:  0

Negative Values Count for FTA:  0
NaN values for FTA:  0

Negative Values Count for FT_PCT:  0
NaN values for FT_PCT:  0

Negative Values Count for OREB:  0
NaN values for OREB:  0

Negative Values Count for DREB:  0
NaN values for DREB:  0

Negative Values Count for REB:  0
NaN values for REB:  0

Negative Values Count for AST:  0
NaN values for AST:  0

Negative Values Count for TOV:  0
NaN values for TOV:  0

Negative Values Count for STL:  0
NaN values for STL:  0

Negative Values Count for BLK:  0
NaN values for BLK:  0

Negative Values Count for BLKA:  0
NaN values for BLKA:  0

Negative Values Count for PF:  0
NaN values for PF:  0

Negative Values Count for PFD:  0
NaN values for PFD:  0

Negative Values Count for PTS:  0
NaN values for PTS:  0

Negative Values Count for PLUS_MINUS:  5220
NaN values for PLUS_MINUS:  0

Negative Values Count for NBA_FANTASY_PTS:  3
NaN values for NBA_FANTASY_PTS:  0

Negative Values Count for DD2:  0
NaN values for DD2:  0

Negative Values Count for TD3:  0
NaN values for TD3:  0

Negative Values Count for WNBA_FANTASY_PTS:  0
NaN values for WNBA_FANTASY_PTS:  0

Negative Values Count for GP_RANK:  0
NaN values for GP_RANK:  0

Negative Values Count for W_RANK:  0
NaN values for W_RANK:  0

Negative Values Count for L_RANK:  0
NaN values for L_RANK:  0

Negative Values Count for W_PCT_RANK:  0
NaN values for W_PCT_RANK:  0

Negative Values Count for MIN_RANK:  0
NaN values for MIN_RANK:  0

Negative Values Count for FGM_RANK:  0
NaN values for FGM_RANK:  0

Negative Values Count for FGA_RANK:  0
NaN values for FGA_RANK:  0

Negative Values Count for FG_PCT_RANK:  0
NaN values for FG_PCT_RANK:  0

Negative Values Count for FG3M_RANK:  0
NaN values for FG3M_RANK:  0

Negative Values Count for FG3A_RANK:  0
NaN values for FG3A_RANK:  0

Negative Values Count for FG3_PCT_RANK:  0
NaN values for FG3_PCT_RANK:  0

Negative Values Count for FTM_RANK:  0
NaN values for FTM_RANK:  0

Negative Values Count for FTA_RANK:  0
NaN values for FTA_RANK:  0

Negative Values Count for FT_PCT_RANK:  0
NaN values for FT_PCT_RANK:  0

Negative Values Count for OREB_RANK:  0
NaN values for OREB_RANK:  0

Negative Values Count for DREB_RANK:  0
NaN values for DREB_RANK:  0

Negative Values Count for REB_RANK:  0
NaN values for REB_RANK:  0

Negative Values Count for AST_RANK:  0
NaN values for AST_RANK:  0

Negative Values Count for TOV_RANK:  0
NaN values for TOV_RANK:  0

Negative Values Count for STL_RANK:  0
NaN values for STL_RANK:  0

Negative Values Count for BLK_RANK:  0
NaN values for BLK_RANK:  0

Negative Values Count for BLKA_RANK:  0
NaN values for BLKA_RANK:  0

Negative Values Count for PF_RANK:  0
NaN values for PF_RANK:  0

Negative Values Count for PFD_RANK:  0
NaN values for PFD_RANK:  0

Negative Values Count for PTS_RANK:  0
NaN values for PTS_RANK:  0

Negative Values Count for PLUS_MINUS_RANK:  0
NaN values for PLUS_MINUS_RANK:  0

Negative Values Count for NBA_FANTASY_PTS_RANK:  0
NaN values for NBA_FANTASY_PTS_RANK:  0

Negative Values Count for DD2_RANK:  0
NaN values for DD2_RANK:  0

Negative Values Count for TD3_RANK:  0
NaN values for TD3_RANK:  0

Negative Values Count for WNBA_FANTASY_PTS_RANK:  0
NaN values for WNBA_FANTASY_PTS_RANK:  0

season_id is not numerical and is type:  object
NaN values for season_id:  0

COUNTRY is not numerical and is type:  object
NaN values for COUNTRY:  0

Negative Values Count for E_OFF_RATING:  0
NaN values for E_OFF_RATING:  0

Negative Values Count for OFF_RATING:  0
NaN values for OFF_RATING:  0

Negative Values Count for sp_work_OFF_RATING:  0
NaN values for sp_work_OFF_RATING:  0

Negative Values Count for E_DEF_RATING:  0
NaN values for E_DEF_RATING:  0

Negative Values Count for DEF_RATING:  0
NaN values for DEF_RATING:  0

Negative Values Count for sp_work_DEF_RATING:  0
NaN values for sp_work_DEF_RATING:  0

Negative Values Count for E_NET_RATING:  5210
NaN values for E_NET_RATING:  0

Negative Values Count for NET_RATING:  5155
NaN values for NET_RATING:  0

Negative Values Count for sp_work_NET_RATING:  5155
NaN values for sp_work_NET_RATING:  0

Negative Values Count for AST_PCT:  0
NaN values for AST_PCT:  0

Negative Values Count for AST_TO:  0
NaN values for AST_TO:  0

Negative Values Count for AST_RATIO:  0
NaN values for AST_RATIO:  0

Negative Values Count for OREB_PCT:  0
NaN values for OREB_PCT:  0

Negative Values Count for DREB_PCT:  0
NaN values for DREB_PCT:  0

Negative Values Count for REB_PCT:  0
NaN values for REB_PCT:  0

Negative Values Count for TM_TOV_PCT:  0
NaN values for TM_TOV_PCT:  0

Negative Values Count for E_TOV_PCT:  0
NaN values for E_TOV_PCT:  0

Negative Values Count for EFG_PCT:  0
NaN values for EFG_PCT:  0

Negative Values Count for TS_PCT:  0
NaN values for TS_PCT:  0

Negative Values Count for USG_PCT:  0
NaN values for USG_PCT:  0

Negative Values Count for E_USG_PCT:  0
NaN values for E_USG_PCT:  0

Negative Values Count for E_PACE:  0
NaN values for E_PACE:  0

Negative Values Count for PACE:  0
NaN values for PACE:  0

Negative Values Count for PACE_PER40:  0
NaN values for PACE_PER40:  0

Negative Values Count for sp_work_PACE:  0
NaN values for sp_work_PACE:  0

Negative Values Count for PIE:  175
NaN values for PIE:  0

Negative Values Count for POSS:  0
NaN values for POSS:  0

Negative Values Count for FGM_PG:  0
NaN values for FGM_PG:  0

Negative Values Count for FGA_PG:  0
NaN values for FGA_PG:  0

Negative Values Count for E_OFF_RATING_RANK:  0
NaN values for E_OFF_RATING_RANK:  0

Negative Values Count for OFF_RATING_RANK:  0
NaN values for OFF_RATING_RANK:  0

Negative Values Count for sp_work_OFF_RATING_RANK:  0
NaN values for sp_work_OFF_RATING_RANK:  0

Negative Values Count for E_DEF_RATING_RANK:  0
NaN values for E_DEF_RATING_RANK:  0

Negative Values Count for DEF_RATING_RANK:  0
NaN values for DEF_RATING_RANK:  0

Negative Values Count for sp_work_DEF_RATING_RANK:  0
NaN values for sp_work_DEF_RATING_RANK:  0

Negative Values Count for E_NET_RATING_RANK:  0
NaN values for E_NET_RATING_RANK:  0

Negative Values Count for NET_RATING_RANK:  0
NaN values for NET_RATING_RANK:  0

Negative Values Count for sp_work_NET_RATING_RANK:  0
NaN values for sp_work_NET_RATING_RANK:  0

Negative Values Count for AST_PCT_RANK:  0
NaN values for AST_PCT_RANK:  0

Negative Values Count for AST_TO_RANK:  0
NaN values for AST_TO_RANK:  0

Negative Values Count for AST_RATIO_RANK:  0
NaN values for AST_RATIO_RANK:  0

Negative Values Count for OREB_PCT_RANK:  0
NaN values for OREB_PCT_RANK:  0

Negative Values Count for DREB_PCT_RANK:  0
NaN values for DREB_PCT_RANK:  0

Negative Values Count for REB_PCT_RANK:  0
NaN values for REB_PCT_RANK:  0

Negative Values Count for TM_TOV_PCT_RANK:  0
NaN values for TM_TOV_PCT_RANK:  0

Negative Values Count for E_TOV_PCT_RANK:  0
NaN values for E_TOV_PCT_RANK:  0

Negative Values Count for EFG_PCT_RANK:  0
NaN values for EFG_PCT_RANK:  0

Negative Values Count for TS_PCT_RANK:  0
NaN values for TS_PCT_RANK:  0

Negative Values Count for USG_PCT_RANK:  0
NaN values for USG_PCT_RANK:  0

Negative Values Count for E_USG_PCT_RANK:  0
NaN values for E_USG_PCT_RANK:  0

Negative Values Count for E_PACE_RANK:  0
NaN values for E_PACE_RANK:  0

Negative Values Count for PACE_RANK:  0
NaN values for PACE_RANK:  0

Negative Values Count for sp_work_PACE_RANK:  0
NaN values for sp_work_PACE_RANK:  0

Negative Values Count for PIE_RANK:  0
NaN values for PIE_RANK:  0

Negative Values Count for FGM_PG_RANK:  0
NaN values for FGM_PG_RANK:  0

Negative Values Count for FGA_PG_RANK:  0
NaN values for FGA_PG_RANK:  0

Names is not numerical and is type:  object
NaN values for Names:  0

Positions is not numerical and is type:  object
NaN values for Positions:  0

Negative Values Count for AAV+Bonus:  0
NaN values for AAV+Bonus:  0

Year_List is not numerical and is type:  object
NaN values for Year_List:  0

We can see that the values do make sense, there are <B>no NaN values</B> in columns that are numeric and string columns are all object types. There are a few negative columns such as in ratings, PIE, or plus-minus column but those seem to make sense as those statistics should have negative values in it. 

This concludes our data manipulation and curation journey, we will next investigate insights into the dataset through our exploratory analysis.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=0b855501-6f2c-4764-816d-be07593df653' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>